# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-19 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='描述')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1, verbose_name='优先级')),
                ('status', models.IntegerField(choices=[(1, '等待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭')], default=1, verbose_name='需求状态')),
                ('closed_reason', models.TextField(blank=True, null=True, verbose_name='关闭原因')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '工单',
            },
        ),
    ]
