# Generated by Django 2.0 on 2019-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20181030_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='expected_at',
            field=models.DateField(blank=True, null=True, verbose_name='预计完成时间'),
        ),
    ]
