# Generated by Django 2.0 on 2019-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20190910_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designworkorder',
            name='status',
            field=models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭')], default=1, verbose_name='状态'),
        ),
    ]
