# Generated by Django 2.0 on 2020-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_auto_20190920_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='期望截止期'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='done_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成确认时间'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭'), (5, '完成待确认'), (6, '关闭待确认')], default=1, verbose_name='状态'),
        ),
    ]
