# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:36
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def data_migrate_work_order_done_confirmed_at(apps, schema_editor):
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    DesignWorkOrder = apps.get_model("workorder", "DesignWorkOrder")
    for item in WorkOrder.objects.all():
        if item.status in [3, 4]:
            if not item.done_at:
                item.done_at = timezone.now()
                item.save()
            if not item.done_confirmed_at:
                item.done_confirmed_at = item.done_at
            item.save()

    for item in DesignWorkOrder.objects.all():
        if item.status in [3, 4]:
            if not item.done_at:
                item.done_at = timezone.now()
                item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('workorder', '0007_auto_20200520_1802'),
    ]

    operations = [
        migrations.RunPython(data_migrate_work_order_done_confirmed_at, migrations.RunPython.noop),
    ]
