# Generated by Django 2.0 on 2020-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_data_migrate_work_order_done_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭'), (5, '待确认完成'), (6, '待确认关闭')], default=1, verbose_name='状态'),
        ),
    ]
