# Generated by Django 2.0 on 2020-10-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0009_auto_20200521_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_type', models.CharField(choices=[('ui_style', '设计-设计风格'), ('ui_global', '设计-整体设计'), ('ui_changes', '设计-设计调整'), ('ui_walkthrough', '设计-设计走查'), ('tpm_deployment', 'TPM-项目部署'), ('tpm_bug', 'TPM-BUG处理'), ('tpm_evaluation', 'TPM-技术评估'), ('tpm_other', 'TPM-其他')], default='other', max_length=50, verbose_name='工单类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '一般'), (3, '紧急')], default=1, verbose_name='优先级')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='标题')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已关闭')], default=1, verbose_name='状态')),
                ('closed_reason', models.TextField(blank=True, null=True, verbose_name='关闭原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='预计完成时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('modify_page_number', models.IntegerField(blank=True, null=True, verbose_name='修改页面数量')),
                ('add_page_number', models.IntegerField(blank=True, null=True, verbose_name='新增页面数量')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='页面数量')),
                ('style_type', models.IntegerField(blank=True, null=True, verbose_name='风格种类')),
                ('page_number_range', models.CharField(blank=True, max_length=20, null=True, verbose_name='页面数量范围')),
                ('practical_page_number', models.IntegerField(blank=True, null=True, verbose_name='实际页面数量')),
                ('bug_link', models.CharField(blank=True, max_length=256, null=True, verbose_name='bug链接')),
                ('data_link', models.CharField(blank=True, max_length=256, null=True, verbose_name='部署资料链接')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_common_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑'), ('assign', '指派'), ('begin', '确认'), ('close', '关闭'), ('reopen', '重启'), ('done', '完成'), ('comment', '评论'), ('modify', '修改预计完成时间'), ('other', '操作')], default='other', max_length=15, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='预计完成日期')),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignee_work_order_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='新分配人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('origin_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_assignee_work_order_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='原分配人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='workorder.CommonWorkOrder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单操作记录',
            },
        ),
    ]
