# Generated by Django 2.0 on 2020-10-27 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0010_commonworkorder_workorderoperationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonworkorder',
            name='closed_reason',
        ),
        migrations.AddField(
            model_name='commonworkorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='关闭人'),
        ),
        migrations.AddField(
            model_name='commonworkorder',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='完成人'),
        ),
        migrations.AddField(
            model_name='commonworkorder',
            name='start_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='开始人'),
        ),
    ]
