# Generated by Django 2.2.14 on 2021-04-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0011_auto_20201027_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='submitter',
        ),
        migrations.DeleteModel(
            name='DesignWorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
