# Generated by Django 2.2.14 on 2021-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_auto_20210426_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworkorder',
            name='work_order_type',
            field=models.CharField(choices=[('ui_style', '设计-设计风格'), ('ui_global', '设计-整体设计'), ('ui_changes', '设计-设计调整'), ('ui_walkthrough', '设计-设计走查'), ('tpm_deployment', 'TPM-项目部署'), ('tpm_bug', 'TPM-BUG处理'), ('tpm_evaluation', 'TPM-技术评估'), ('tpm_other', 'TPM-其他'), ('other', '其他')], default='other', max_length=50, verbose_name='工单类型'),
        ),
    ]
