# Generated by Django 2.0 on 2018-11-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prototypes.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '类型',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '平台',
            },
        ),
        migrations.CreateModel(
            name='PrototypeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=prototypes.models.PrototypeReference.generate_filename)),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='prototypes', to='prototypes.Category', verbose_name='类型')),
                ('platforms', models.ManyToManyField(related_name='prototypes', to='prototypes.Platform', verbose_name='平台')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototype_references', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '原型参考',
            },
        ),
    ]
