# Generated by Django 2.0 on 2018-12-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prototypes', '0002_init_platform_categoty_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='prototype_collections', to='prototypes.Category', verbose_name='类型')),
                ('platforms', models.ManyToManyField(related_name='prototype_collections', to='prototypes.Platform', verbose_name='平台')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototype_collections', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '原型参考集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='prototypereference',
            options={'ordering': ['-is_cover', '-created_at'], 'verbose_name': '原型参考'},
        ),
        migrations.AddField(
            model_name='prototypereference',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='prototypereference',
            name='filename',
            field=models.CharField(max_length=128, verbose_name='文件名称'),
        ),
        migrations.AddField(
            model_name='prototypereference',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prototype_references', to='prototypes.Collection', verbose_name='提交人'),
        ),
    ]
