# Generated by Django 2.0 on 2019-01-03 13:39

from django.db import migrations
import easy_thumbnails.fields
import prototypes.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0004_init_platform_categoty_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypereference',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=prototypes.models.PrototypeReference.generate_filename),
        ),
    ]
