# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField(blank=True, null=True, verbose_name='报酬')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='developers.Developer', verbose_name='工程师')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='预计结束时间')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.IntegerField(choices=[(1, '未联系'), (2, '收集信息'), (3, '撰写报告'), (4, '等待反馈'), (5, 'PRD'), (6, '设计'), (7, '开发'), (8, '测试'), (9, '交付'), (10, '完成'), (11, '未成单')], default=1, verbose_name='项目状态')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='预计结束时间')),
                ('done_at', models.DateField(blank=True, null=True, verbose_name='实际结束时间')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.Client', verbose_name='客户')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('expected_at', models.DateField(verbose_name='预计结束时间')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='项目')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.Task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='projects.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Role', verbose_name='职位'),
        ),
    ]
