# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_data_migrate_comment_to_status_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('expected_start_at', models.DateField(blank=True, null=True, verbose_name='预计开始日期')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '正常'), (2, '警告')], default=0, verbose_name='阶段状态')),
                ('remark', models.TextField(verbose_name='备注')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.Project', verbose_name='项目')),
            ],
        ),
    ]
