# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='expected_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计完成日期'),
        ),
    ]
