# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_phase_expected_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='track_code',
            field=models.TextField(blank=True, null=True, verbose_name='追踪码'),
        ),
    ]
