# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_data_migrate_project_track_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='expected_done_at',
            field=models.DateField(blank=True, null=True, verbose_name='预计完成日期'),
        ),
    ]
