# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170302_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
