# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 16:56
from __future__ import unicode_literals

from django.contrib.contenttypes.management import create_contenttypes
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def populate_logs(apps, schema_editor):
    app_config = apps.get_app_config('projects')
    app_config.models_module = app_config.models_module or True

    create_contenttypes(app_config)

    Log = apps.get_model("projects", "Log")
    project_type = ContentType.objects.get(app_label="projects", model="project")
    for log in Log.objects.all():
        log.content_type_id = project_type.id
        log.object_id = log.project_id
        log.save()


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0011_auto_20170330_1654'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_logs, migrations.RunPython.noop),
    ]
