# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_data_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='project',
        ),
        migrations.RemoveField(
            model_name='log',
            name='task',
        ),
    ]
