# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 20:30
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def populate_tasks(apps, schema_editor):
    Task = apps.get_model("projects", "Task")
    project_type = ContentType.objects.get(app_label="projects", model="project")
    for task in Task.objects.all():
        task.content_type_id = project_type.id
        task.object_id = task.project_id
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170330_2028'),
    ]

    operations = [
        migrations.RunPython(populate_tasks, migrations.RunPython.noop),
    ]
