# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def move_status_comments_to_comments(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    StatusComment = apps.get_model("projects", "StatusComment")
    Project = apps.get_model("projects", "Project")
    project_type = ContentType.objects.get(app_label="projects", model="project")

    for status_comment in StatusComment.objects.filter(is_public = False):
        project = Project.objects.get(id=status_comment.project_id)
        comment = Comment(
            content_type_id = project_type.id,
            object_id = project.id,
            author = status_comment.author,
            content = status_comment.content,
        )
        comment.save()
        comment.created_at = status_comment.created_at
        comment.save()
        status_comment.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170408_2246'),
    ]

    operations = [
        migrations.RunPython(move_status_comments_to_comments, migrations.RunPython.noop),
    ]
