# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_statuscomment_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.Client', verbose_name='项目客户'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_projects', to=settings.AUTH_USER_MODEL, verbose_name='产品经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='项目开始时间'),
        ),
    ]
