# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20170612_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('communication', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('bug', models.IntegerField()),
                ('code_style', models.IntegerField()),
                ('job_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_review', serialize=False, to='projects.JobPosition')),
            ],
        ),
    ]
