# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.conf import settings


def move_developer_review_to_job_review(apps, schema_editor):
    if "developer_review" not in settings.INSTALLED_APPS:
        return
    try:
        DeveloperReview = apps.get_model("developer_review", "DeveloperReview")
    except LookupError:
        return
    JobReview = apps.get_model("projects", "JobReview")

    for develop_review in DeveloperReview.objects.all():
        job_review = JobReview(
            communication=develop_review.communication,
            efficiency=develop_review.efficiency,
            quality=develop_review.quality,
            bug=develop_review.bug,
            code_style=develop_review.code_style,
            job_position=develop_review.job_position,
        )
        job_review.save()


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0021_jobreview'),
    ]

    operations = [
        migrations.RunPython(move_developer_review_to_job_review, migrations.RunPython.noop),
    ]
