# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_data_move_developer_review_to_job_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobreview',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
