# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170731_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_playbook', 'Can see playbook in projects'), ('view_30_finished_projects', 'Can see 30 finished projects'), ('view_project_finished_in_60_days', 'Can see finished projects in 60 days'), ('view_job_positions', 'Can see job positions in projects'), ('view_all_projects', 'Can see all projects'))},
        ),
    ]
