# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-27 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20171015_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
