# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20171127_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposition',
            options={'verbose_name': '开发岗位'},
        ),
        migrations.AlterModelOptions(
            name='jobreview',
            options={'verbose_name': '工程师评价'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_playbook', 'Can see playbook in projects'), ('view_30_finished_projects', 'Can see 30 finished projects'), ('view_project_finished_in_60_days', 'Can see finished projects in 60 days'), ('view_job_positions', 'Can see job positions in projects'), ('view_all_projects', 'Can see all projects')), 'verbose_name': '项目'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务'},
        ),
    ]
