# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20171128_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreview',
            name='bug',
            field=models.IntegerField(verbose_name='BUG数量'),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='code_style',
            field=models.IntegerField(verbose_name='代码质量'),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='communication',
            field=models.IntegerField(verbose_name='交流沟通'),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='efficiency',
            field=models.IntegerField(verbose_name='开发速度'),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='quality',
            field=models.IntegerField(verbose_name='功能质量'),
        ),
    ]
