# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20171224_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('gear_view_all_projects', '查看全部项目'), ('gear_view_ongoing_projects', '查看进行中的项目'), ('gear_view_project_finished_in_60_days', '查看最近60天内结束的项目'), ('gear_view_playbook', '查看项目playbook'), ('gear_view_all_job_positions', '查看全部有开发职位')), 'verbose_name': '项目'},
        ),
    ]
