# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0032_permission_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='检查点名称')),
                ('expected_at', models.DateField(verbose_name='预计完成时间')),
                ('done_at', models.DateField(blank=True, null=True, verbose_name='实际完成时间')),
                ('status', models.IntegerField(
                    choices=[(0, '未完成'), (1, '正常完成'), (2, '存在风险'), (3, '合理延期'), (4, '出现问题'), (5, '该项目或该阶段无此项'),
                             (6, '项目终止')], default=0, verbose_name='状态'),
                 ),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='previous', to='projects.CheckPoint', verbose_name='下一个检查点')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints',
                                                to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints',
                                              to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目检查点',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='项目启动时间')),
                ('prd_confirmation_time', models.DateField(blank=True, null=True, verbose_name='PRD确认时间')),
                ('ui_confirmation_time', models.DateField(blank=True, null=True, verbose_name='UI确认时间')),
                ('dev_start_time', models.DateField(blank=True, null=True, verbose_name='开发开始时间')),
                ('dev_midpoint_time', models.DateField(blank=True, null=True, verbose_name='开发中期时间')),
                ('dev_completion_time', models.DateField(blank=True, null=True, verbose_name='开发结束时间')),
                ('delivery_time', models.DateField(blank=True, null=True, verbose_name='交付验收时间')),
                ('is_modified', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule',
                                                 to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目日程表',
            },
        ),
    ]
