# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-11 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('projects', '0034_create_schedule_for_previous_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='auth.Group', verbose_name='负责职位'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目日程表修改时间'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='项目日程表被修改'),
        ),
    ]
