# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20180111_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['position'], 'verbose_name': '项目检查点'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('gear_view_all_projects', '查看全部项目'), ('gear_view_ongoing_projects', '查看进行中的项目'), ('gear_view_project_finished_in_60_days', '查看最近60天内结束的项目'), ('gear_view_playbook', '查看项目playbook'), ('gear_view_all_job_positions', '查看全部有开发职位'), ('gear_view_project_track_progress', '查看项目跟踪界面')), 'verbose_name': '项目'},
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='next',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='position',
            field=models.IntegerField(default=-1, verbose_name='位置'),
        ),
    ]
