# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_permission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='项目日程表修改时间'),
        ),
    ]
