# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20180116_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='项目日程表修改时间'),
        ),
    ]
