# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20180116_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.DeliveryDocument.generate_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名称')),
                ('uid', models.CharField(max_length=25, verbose_name='标识码')),
                ('cipher', models.CharField(blank=True, max_length=6, null=True, verbose_name='提取码')),
            ],
            options={
                'verbose_name': '项目交付文档',
                'ordering': ['document_type__number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='文档类别')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='文档后缀')),
                ('number', models.IntegerField(verbose_name='文档类别编号')),
            ],
            options={
                'verbose_name': '项目交付文档类别',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.DeliveryDocumentType', verbose_name='交付文档类别'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='projects.Project', verbose_name='项目'),
        ),
    ]
