# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-29 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_create_project_delivery_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='principal',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
