# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20180129_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydocument',
            name='is_behind',
            field=models.BooleanField(default=False),
        ),
    ]
