# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_deliverydocument_is_behind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydocument',
            options={'ordering': ['document_type__number'], 'verbose_name': '交付文件'},
        ),
        migrations.AlterModelOptions(
            name='deliverydocumenttype',
            options={'ordering': ['number'], 'verbose_name': '交付文件类别'},
        ),
        migrations.AlterField(
            model_name='deliverydocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.DeliveryDocumentType', verbose_name='交付文件类别'),
        ),
        migrations.AlterField(
            model_name='deliverydocumenttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='文件类别名'),
        ),
        migrations.AlterField(
            model_name='deliverydocumenttype',
            name='number',
            field=models.IntegerField(verbose_name='文件类别编号'),
        ),
        migrations.AlterField(
            model_name='deliverydocumenttype',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='后缀'),
        ),
    ]
