# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_change_delivery_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydocument',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称'),
        ),
    ]
