# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20180208_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('payment_account_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款账户')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='总金额')),
                ('first_stage_amount', models.FloatField(blank=True, null=True, verbose_name='第一阶段金额')),
                ('first_stage_paid_at', models.DateField(blank=True, null=True, verbose_name='第一阶段打款日期')),
                ('second_stage_amount', models.FloatField(blank=True, null=True, verbose_name='第二阶段金额')),
                ('second_stage_paid_at', models.DateField(blank=True, null=True, verbose_name='第二阶段打款日期')),
                ('third_stage_amount', models.FloatField(blank=True, null=True, verbose_name='第三阶段金额')),
                ('third_stage_paid_at', models.DateField(blank=True, null=True, verbose_name='第三阶段打款日期')),
                ('fourth_stage_amount', models.FloatField(blank=True, null=True, verbose_name='第四阶段金额')),
                ('fourth_stage_paid_at', models.DateField(blank=True, null=True, verbose_name='第四阶段打款日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目打款记录',
            },
        ),
    ]
