# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_permission_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('gear_view_all_projects', '查看全部项目'), ('gear_view_ongoing_projects', '查看进行中的项目'), ('gear_view_project_finished_in_60_days', '查看最近60天内结束的项目'), ('gear_view_playbook', '查看项目playbook'), ('gear_view_all_job_positions', '查看全部有开发职位'), ('gear_view_project_track_progress', '查看项目跟踪界面'), ('gear_view_all_my_responsible_projects_roles_payments', '查看我负责的项目的所有工程师及其打款记录'), ('gear_view_all_project_payments', '查看全部项目打款'), ('gear_view_ongoing_project_payments', '查看进行中项目打款')), 'verbose_name': '项目'},
        ),
        migrations.AlterModelOptions(
            name='projectpayment',
            options={'ordering': ['-created_at'], 'verbose_name': '项目打款记录'},
        ),
    ]
