# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_permission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='first_stage_has_invoice',
            field=models.BooleanField(default=False, verbose_name='第一阶段打款开发票'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='fourth_stage_has_invoice',
            field=models.BooleanField(default=False, verbose_name='第四阶段打款开发票'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='second_stage_has_invoice',
            field=models.BooleanField(default=False, verbose_name='第二阶段打款开发票'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='third_stage_has_invoice',
            field=models.BooleanField(default=False, verbose_name='第三阶段打款开发票'),
        ),
    ]
