# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20180314_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='合同名')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='合同号')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='入档日期')),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.models.ProjectContract.generate_filename)),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.Project', verbose_name='项目')),
            ],
        ),
    ]
