# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_permission_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontract',
            options={'ordering': ['-created_at'], 'verbose_name': '项目合同'},
        ),
    ]
