# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_ exchange_project_payment_name_and_payment_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='review_status',
            field=models.IntegerField(choices=[(0, '未评分'), (1, '已评分'), (2, '跳过评分')], default=0, verbose_name='评分状态'),
        ),
    ]
