# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-28 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0059_init_job_position_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_projects', to=settings.AUTH_USER_MODEL, verbose_name='技术产品经理'),
        ),
    ]
