# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_update_all_projects_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
