# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_perms_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypeCommentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=100, verbose_name='锚链接')),
                ('panel_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='所属板块')),
                ('position_left', models.IntegerField(verbose_name='相对所属板块左上角left值')),
                ('position_top', models.IntegerField(verbose_name='相对所属板块左上角top值')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_points', to='projects.ProjectPrototype', verbose_name='原型')),
            ],
            options={
                'verbose_name': '项目评论点',
                'ordering': ['prototype', 'url_hash'],
            },
        ),
    ]
