# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-13 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0070_set_view_pm_statistical_data_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprototype',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_prototypes', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
