# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_projectprototype_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '项目甘特图角色',
            },
        ),
        migrations.CreateModel(
            name='GanttTaskCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='模块分类名称')),
                ('number', models.IntegerField(verbose_name='模块编号')),
            ],
            options={
                'verbose_name': '项目甘特图模块分类',
            },
        ),
        migrations.CreateModel(
            name='GanttTaskTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='模块任务名称')),
                ('number', models.IntegerField(verbose_name='模块任务编号')),
                ('start_time', models.DateField(verbose_name='任务开始时间')),
                ('timedelta_days', models.FloatField(verbose_name='任务持续天数')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_topics', to='projects.GanttTaskCatalogue', verbose_name='模块分类')),
            ],
            options={
                'verbose_name': '项目甘特图模块任务',
            },
        ),
        migrations.CreateModel(
            name='ProjectGanttChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_chart', to='projects.Project')),
            ],
            options={
                'verbose_name': '项目甘特图',
            },
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='gantt_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_topics', to='projects.ProjectGanttChart', verbose_name='项目甘特图'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_topics', to='projects.GanttRole', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='gantttaskcatalogue',
            name='gantt_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_catalogues', to='projects.ProjectGanttChart', verbose_name='项目甘特图'),
        ),
        migrations.AddField(
            model_name='ganttrole',
            name='gantt_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.ProjectGanttChart', verbose_name='项目甘特图'),
        ),
    ]
