# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_projectprototype_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_info',
            field=models.TextField(blank=True, null=True, verbose_name='部署测试信息'),
        ),
    ]
