# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-03 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0018_auto_20180903_1418'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0072_project_deployment_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPositionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待确认'), (1, '已确认'), (2, '已拒绝'), (3, '未选择')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('contact_at', models.DateTimeField(blank=True, null=True, verbose_name='联系时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_candidates', to='developers.Developer', verbose_name='工程师')),
            ],
            options={
                'verbose_name': '开发岗位候选人',
            },
        ),
        migrations.CreateModel(
            name='JobPositionNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('expected_confirmation_time', models.DateField(verbose_name='预计确认时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('done_at', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_position_needs', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_needs', to='projects.Project', verbose_name='项目')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Role', verbose_name='职位')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_position_needs', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '开发岗位需求',
            },
        ),
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='position_need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='projects.JobPositionNeed', verbose_name='开发岗位需求'),
        ),
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_position_candidates', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
