# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-04 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20180824_1128'),
        ('projects', '0072_project_deployment_info'),
    ]

    operations = [
    ]
