# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_merge_20180904_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gantttaskcatalogue',
            options={'ordering': ['number'], 'verbose_name': '项目甘特图模块分类'},
        ),
        migrations.AlterModelOptions(
            name='gantttasktopic',
            options={'ordering': ['number'], 'verbose_name': '项目甘特图模块任务'},
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
    ]
