# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20180905_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttasktopic',
            name='expected_finish_time',
            field=models.DateField(blank=True, null=True, verbose_name='任务预计完成时间'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='half_day_position',
            field=models.CharField(blank=True, choices=[('start_time', '起始日期'), ('finish_time', '完成日期')], max_length=20, null=True, verbose_name='半天所在位置'),
        ),
    ]
