# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_auto_20180907_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttasktopic',
            name='only_workday',
            field=models.BooleanField(default=True, verbose_name='仅计算工作日'),
        ),
    ]
