# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-14 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0076_gantttasktopic_only_workday'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_projects', to=settings.AUTH_USER_MODEL, verbose_name='测试工程师'),
        ),
    ]
