# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-14 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_update_all_projects_checkpoints'),
        ('projects', '0077_project_test_engineer'),
    ]

    operations = [
    ]
