# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-14 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20180903_1418'),
        ('projects', '0078_merge_20180914_2031'),
    ]

    operations = [
    ]
