# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_merge_20180914_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='refuse_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝理由'),
        ),
    ]
