# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_jobpositioncandidate_refuse_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositionneed',
            name='status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已确认工程师'), (3, '已取消')], default=0, verbose_name='状态'),
        ),
    ]
