# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_jobpositionneed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpositionneed',
            name='status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '已确认工程师'), (2, '已取消')], default=0, verbose_name='状态'),
        ),
    ]
