# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-18 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20180920_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ganttrole',
            options={'ordering': ['id'], 'verbose_name': '项目甘特图角色'},
        ),
    ]
