# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_auto_20181018_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectganttchart',
            name='uid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
