# Generated by Django 2.0 on 2019-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_auto_20181213_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(5, 'PRD'), (6, '设计'), (7, '开发'), (8, '测试'), (9, '验收'), (10, '完成')], default=1, verbose_name='项目状态'),
        ),
    ]
