# Generated by Django 2.0 on 2019-01-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_update_all_projects_checkpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('period_days', models.IntegerField(default=0, verbose_name='周期天数')),
                ('start_time', models.DateField(verbose_name='启动时间')),
                ('delivery_time', models.DateField(verbose_name='交付时间')),
                ('start', models.TextField(blank=True, null=True, verbose_name='项目启动')),
                ('requirement_confirmation', models.TextField(blank=True, null=True, verbose_name='需求确认')),
                ('ui_design', models.TextField(blank=True, null=True, verbose_name='UI设计')),
                ('development', models.TextField(blank=True, null=True, verbose_name='项目开发')),
                ('test', models.TextField(blank=True, null=True, verbose_name='项目测试')),
                ('acceptance', models.TextField(blank=True, null=True, verbose_name='交付验收')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目客户日程表',
            },
        ),
    ]
