# Generated by Django 2.0 on 2019-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_update_all_projects_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='period',
            field=models.FloatField(blank=True, null=True, verbose_name='开发周数'),
        ),
        migrations.AddField(
            model_name='jobpositionneed',
            name='period',
            field=models.FloatField(blank=True, null=True, verbose_name='开发周数'),
        ),
    ]
