# Generated by Django 2.0 on 2019-01-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20190121_1607'),
        ('projects', '0091_auto_20190118_1735'),
    ]

    operations = [
    ]
