# Generated by Django 2.0 on 2019-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_update_all_projects_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalendar',
            name='holiday',
            field=models.TextField(blank=True, null=True, verbose_name='节假日'),
        ),
    ]
