# Generated by Django 2.0 on 2019-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_clientcalendar_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='确认'),
        ),
    ]
