# Generated by Django 2.0 on 2019-03-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0096_update_projects_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_projects', to=settings.AUTH_USER_MODEL, verbose_name='客户成功'),
        ),
    ]
