# Generated by Django 2.0 on 2019-04-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_project_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypecommentpoint',
            name='page_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='页面名字'),
        ),
        migrations.AlterField(
            model_name='prototypecommentpoint',
            name='url_hash',
            field=models.CharField(max_length=150, verbose_name='锚链接'),
        ),
    ]
