# Generated by Django 2.0 on 2019-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_jobpositioncandidate_is_first_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganttrole',
            name='role_type',
            field=models.CharField(blank=True, choices=[('pm', '产品经理'), ('mentor', '导师'), ('tpm', '技术产品经理'), ('test', '测试'), ('developer', '开发工程师'), ('csm', '客户成功'), ('other', '其他')], max_length=15, null=True, verbose_name='角色类型'),
        ),
    ]
