# Generated by Django 2.0 on 2019-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_migrate_all_gantt_tasks_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='first_stage_received_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='第一阶段已收金额'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='fourth_stage_received_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='第四阶段已收金额'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='need_invoice',
            field=models.BooleanField(default=True, verbose_name='需要发票'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='second_stage_received_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='第二阶段已收金额'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='status',
            field=models.CharField(choices=[('ongoing', '进行中'), ('finished', '正常完成'), ('abend', '异常终止')], default='ongoing', max_length=50, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='third_stage_received_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='第三阶段已收金额'),
        ),
    ]
