# Generated by Django 2.0 on 2019-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_migrate_all_projects_payments_total_amount_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='role_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='职位备注'),
        ),
        migrations.AddField(
            model_name='jobpositionneed',
            name='role_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='职位备注'),
        ),
        migrations.AlterField(
            model_name='jobpositionneed',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='岗位描述'),
        ),
    ]
