# Generated by Django 2.0 on 2019-07-11 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0106_auto_20190708_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='部署时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_servers',
            field=models.TextField(blank=True, null=True, verbose_name='部署服务器信息'),
        ),
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_test_projects', to=settings.AUTH_USER_MODEL, verbose_name='测试工程师'),
        ),
    ]
