# Generated by Django 2.0 on 2019-07-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_migrate_all_projects_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_engineer',
        ),
        migrations.AlterField(
            model_name='project',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_projects', to=settings.AUTH_USER_MODEL, verbose_name='测试工程师'),
        ),
    ]
