# Generated by Django 2.0 on 2019-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_auto_20190711_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='codename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检查点名称'),
        ),
    ]
