# Generated by Django 2.0 on 2019-07-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_migrate_checkpoint_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganttrole',
            name='role_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='角色类型'),
        ),
    ]
