# Generated by Django 2.0 on 2019-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_migrate_gantt_role_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_project', models.TextField(blank=True, null=True, verbose_name='GitLab项目')),
                ('api_document', models.TextField(blank=True, null=True, verbose_name='接口文档')),
                ('ui_link', models.TextField(blank=True, null=True, verbose_name='UI设计稿')),
                ('engineer_contact_docs', models.TextField(blank=True, null=True, verbose_name='工程师沟通Quip文件夹')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目链接',
            },
        ),
    ]
