# Generated by Django 2.0 on 2019-09-03 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0114_projectlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpositionneed',
            options={'ordering': ['-created_at'], 'verbose_name': '开发岗位需求'},
        ),
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_position_candidates', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='initial_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初次联系时间'),
        ),
        migrations.AlterField(
            model_name='jobpositioncandidate',
            name='contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='反馈时间'),
        ),
    ]
