# Generated by Django 2.0 on 2019-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_projectlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlinks',
            name='gitlab_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='GitLab组ID'),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='gitlab_project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='GitLab项目ID'),
        ),
    ]
