# Generated by Django 2.0 on 2019-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0115_auto_20190903_1904'),
        ('projects', '0115_auto_20190909_1824'),
    ]

    operations = [
    ]
