# Generated by Django 2.0 on 2019-09-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_project_designer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpositioncandidate',
            options={'ordering': ['created_at'], 'verbose_name': '开发岗位候选人'},
        ),
    ]
