# Generated by Django 2.0 on 2019-09-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0023_developer_gitlab_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0118_auto_20190920_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganttrole',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_roles', to='developers.Developer', verbose_name='工程师'),
        ),
        migrations.AddField(
            model_name='ganttrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
