# Generated by Django 2.0 on 2019-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0119_auto_20190929_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttasktopic',
            name='dev_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开发者完成时间'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='is_dev_done',
            field=models.BooleanField(default=False, verbose_name='开发者已完成'),
        ),
    ]
