# Generated by Django 2.0 on 2019-10-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0120_auto_20191008_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttasktopic',
            name='dev_done_type',
            field=models.CharField(blank=True, choices=[('self', '独立勾选'), ('auto', '自动勾选')], max_length=20, null=True, verbose_name='开发确认完成类型'),
        ),
    ]
