# Generated by Django 2.0 on 2019-10-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0121_gantttasktopic_dev_done_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(5, '原型'), (6, '设计'), (7, '开发'), (8, '测试'), (9, '验收'), (10, '完成')], default=1, verbose_name='项目状态'),
        ),
    ]
