# Generated by Django 2.0 on 2019-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_auto_20191031_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='prd_confirmation_time',
            field=models.DateField(blank=True, null=True, verbose_name='原型确认时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ui_confirmation_time',
            field=models.DateField(blank=True, null=True, verbose_name='设计确认时间'),
        ),
    ]
