# Generated by Django 2.0 on 2019-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0124_auto_20191031_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='schedule_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='进度备注'),
        ),
    ]
