# Generated by Django 2.0 on 2019-11-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0125_project_schedule_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileDevelopmentSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sprint名称')),
                ('position', models.IntegerField(default=0, verbose_name='位置编号')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_sprints',
                                   to='projects.Project', verbose_name='项目')),
                ('schedule',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_sprints',
                                   to='projects.Schedule', verbose_name='日程表')),
            ],
            options={
                'verbose_name': '敏捷开发Sprint',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='review_meeting_time',
            field=models.DateField(blank=True, null=True, verbose_name='内部评审会'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='test_completion_time',
            field=models.DateField(blank=True, null=True, verbose_name='测试结束'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='test_start_time',
            field=models.DateField(blank=True, null=True, verbose_name='测试开始'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ui_start_time',
            field=models.DateField(blank=True, null=True, verbose_name='设计开始'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delivery_time',
            field=models.DateField(blank=True, null=True, verbose_name='交付验收'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dev_completion_time',
            field=models.DateField(blank=True, null=True, verbose_name='开发结束'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dev_midpoint_time',
            field=models.DateField(blank=True, null=True, verbose_name='开发中期'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dev_start_time',
            field=models.DateField(blank=True, null=True, verbose_name='开发开始'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='prd_confirmation_time',
            field=models.DateField(blank=True, null=True, verbose_name='原型确认'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='项目启动'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ui_confirmation_time',
            field=models.DateField(blank=True, null=True, verbose_name='设计确认'),
        ),
    ]
