# Generated by Django 2.0 on 2019-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0128_migrate_projects_checkpoints_name_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agiledevelopmentsprint',
            options={'ordering': ['position'], 'verbose_name': '敏捷开发Sprint'},
        ),
        migrations.AlterField(
            model_name='clientcalendar',
            name='acceptance',
            field=models.TextField(blank=True, null=True, verbose_name='交付审核'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delivery_time',
            field=models.DateField(blank=True, null=True, verbose_name='交付审核'),
        ),
    ]
