# Generated by Django 2.0 on 2019-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0129_auto_20191126_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttasktopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
