# Generated by Django 2.0 on 2019-12-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0131_migrate_projects_gantt_tasks_catalogues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantttaskcatalogue',
            name='number',
            field=models.IntegerField(default=1, verbose_name='模块编号'),
        ),
        migrations.AlterField(
            model_name='gantttasktopic',
            name='number',
            field=models.IntegerField(default=1, verbose_name='模块任务编号'),
        ),
    ]
