# Generated by Django 2.0 on 2019-12-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0132_auto_20191210_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantttasktopic',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_topics', to='projects.GanttTaskCatalogue', verbose_name='模块分类'),
        ),
    ]
