# Generated by Django 2.0 on 2019-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0133_auto_20191210_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttaskcatalogue',
            name='auto_created',
            field=models.BooleanField(default=False, verbose_name='是模板自动创建'),
        ),
        migrations.AddField(
            model_name='gantttasktopic',
            name='auto_created',
            field=models.BooleanField(default=False, verbose_name='是模板自动创建'),
        ),
        migrations.AddField(
            model_name='projectganttchart',
            name='template_init_status',
            field=models.CharField(choices=[('uninitialized', '未初始化'), ('skipped', '跳过'), ('initialized', '已初始化')], default='skipped', max_length=20, verbose_name='模板导入状态'),
        ),
    ]
