# Generated by Django 2.0 on 2019-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0135_auto_20191217_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agiledevelopmentsprint',
            name='end_time',
            field=models.DateField(verbose_name='结束时间'),
        ),
    ]
