# Generated by Django 2.0 on 2019-12-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0138_migrate_projects_checkpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='schedule_remarks',
        ),
    ]
