# Generated by Django 2.0 on 2020-01-08 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0139_remove_project_schedule_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalendar',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_calendars', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
