# Generated by Django 2.0 on 2020-03-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0030_auto_20200116_0014'),
        ('projects', '0140_clientcalendar_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperDailyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(choices=[('undone', '未完成'), ('done', '完成')], default='unfinished', max_length=15, verbose_name='工作状态')),
                ('work_content', models.TextField(blank=True, null=True, verbose_name='工作内容')),
                ('leave_at', models.TimeField(blank=True, null=True, verbose_name='请假开始时间')),
                ('return_at', models.TimeField(blank=True, null=True, verbose_name='请假结束时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('undone_work_content', models.TextField(blank=True, null=True, verbose_name='未完成内容')),
                ('undone_reason', models.TextField(blank=True, null=True, verbose_name='未完成原因')),
                ('day', models.DateField(verbose_name='日期')),
                ('is_punched', models.BooleanField(default=False, verbose_name='已打卡')),
                ('punched_at', models.DateTimeField(blank=True, null=True, verbose_name='打卡时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_works', to='developers.Developer', verbose_name='工程师')),
                ('next_day_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.DeveloperDailyWork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_daily_works', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '工作日报',
            },
        ),
    ]
