# Generated by Django 2.0 on 2020-03-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0142_migrate_projects_product_manager_project_manager'),
        ('projects', '0141_developerdailywork'),
    ]

    operations = [
    ]
