# Generated by Django 2.0 on 2020-03-13 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0143_merge_20200312_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_manage_projects', to=settings.AUTH_USER_MODEL, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpm_projects', to=settings.AUTH_USER_MODEL, verbose_name='技术项目经理'),
        ),
    ]
