# Generated by Django 2.0 on 2020-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0144_auto_20200313_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositioncandidate',
            name='refuse_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝备注'),
        ),
    ]
