# Generated by Django 2.0 on 2020-04-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0146_auto_20200422_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
