# Generated by Django 2.0 on 2020-04-27 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0147_auto_20200424_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='检查点名称')),
                ('flag', models.CharField(blank=True, max_length=15, null=True, verbose_name='标志')),
                ('status', models.CharField(choices=[('pending', '未完成'), ('skipped', '跳过'), ('done', '完成')], default='pending', max_length=15, verbose_name='状态')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='预计完成时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_checkpoints', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_checkpoints', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目技术检查点',
                'ordering': ['expected_at'],
            },
        ),
    ]
