# Generated by Django 2.0 on 2020-04-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0148_technologycheckpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='review_meeting_time',
        ),
    ]
