# Generated by Django 2.0 on 2020-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0149_remove_schedule_review_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlinks',
            name='quip_engineer_folder_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工程师沟通Quip文件夹ID'),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='quip_folder_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip文件夹ID'),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='quip_folder_type',
            field=models.CharField(choices=[('auto', '自动创建'), ('select', '选择'), ('no_need', '不需要')], default='no_need', max_length=10, verbose_name='Quip文件夹类别'),
        ),
    ]
