# Generated by Django 2.0 on 2020-05-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0151_migrate_projects_engineer_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlinks',
            name='engineer_contact_folder',
        ),
    ]
