# Generated by Django 2.0 on 2020-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0152_remove_projectlinks_engineer_contact_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlinks',
            name='quip_tpm_folder_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TPM产出物Quip文件夹ID'),
        ),
        migrations.AddField(
            model_name='technologycheckpoint',
            name='quip_document_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip文档ID'),
        ),
    ]
