# Generated by Django 2.0 on 2020-05-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0153_auto_20200522_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlinks',
            name='quip_tpm_folder_id',
        ),
        migrations.AddField(
            model_name='technologycheckpoint',
            name='quip_document_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip文档标题'),
        ),
    ]
