# Generated by Django 2.0 on 2020-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0154_auto_20200525_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologycheckpoint',
            name='quip_document_ids',
            field=models.TextField(blank=True, null=True, verbose_name='Quip文档集'),
        ),
    ]
