# Generated by Django 2.0 on 2020-08-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_client'),
        ('projects', '0159_auto_20200805_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_clients', to='clients.Client', verbose_name='客户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_clients', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目客户',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(through='projects.ProjectClient', to='clients.Client', verbose_name='项目客户'),
        ),
    ]
