# Generated by Django 2.0 on 2020-08-06 14:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0160_auto_20200805_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('prototype', '原型'), ('design', '设计'), ('demo_server', '测试地址'), ('delivery_document', '交付文档')], max_length=46, null=True, verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='projectprototype',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公开状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectClient', to='clients.Client', verbose_name='项目客户'),
        ),
    ]
