# Generated by Django 2.0 on 2020-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0161_auto_20200806_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalendar',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公开状态'),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='ui_links',
            field=models.TextField(blank=True, null=True, verbose_name='UI设计稿集'),
        ),
    ]
