# Generated by Django 2.0 on 2020-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0164_auto_20200828_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprototype',
            name='oss_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='oss访问地址'),
        ),
    ]
