# Generated by Django 2.0 on 2020-10-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0165_projectprototype_oss_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReferenceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, '跳过')], default=0, verbose_name='交流沟通')),
                ('efficiency', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, '跳过')], default=0, verbose_name='开发速度')),
                ('quality', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, '跳过')], default=0, verbose_name='功能质量')),
                ('execute', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, '跳过')], default=0, verbose_name='执行')),
                ('remarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工程师参考评分',
            },
        ),
        migrations.CreateModel(
            name='JobStandardScore',
            fields=[
                ('communication', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='交流沟通')),
                ('efficiency', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='开发速度')),
                ('quality', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='功能质量')),
                ('execute', models.IntegerField(choices=[(0, '未评分'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='执行')),
                ('job_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_standard_scores', serialize=False, to='projects.JobPosition')),
                ('remarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('evaluate', models.CharField(blank=True, max_length=256, null=True, verbose_name='工程师评价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_standard_scores', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
            options={
                'verbose_name': '工程师标准评分',
            },
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='review_status',
            field=models.IntegerField(choices=[(0, '未评分'), (1, '已评分')], default=0, verbose_name='评分状态'),
        ),
        migrations.AddField(
            model_name='jobreferencescore',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reference_scores', to='projects.JobPosition'),
        ),
        migrations.AddField(
            model_name='jobreferencescore',
            name='score_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reference_scores', to=settings.AUTH_USER_MODEL, verbose_name='评分人'),
        ),
    ]
