# Generated by Django 2.0 on 2020-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0166_auto_20201014_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreferencescore',
            name='remarks',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='evaluate',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='工程师评价'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='remarks',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
    ]
