# Generated by Django 2.0 on 2020-10-30 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0168_data_migrate_projects_job_position_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='review_status',
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='job_position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_standard_score', serialize=False, to='projects.JobPosition'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='score_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_standard_scores', to=settings.AUTH_USER_MODEL, verbose_name='评分人'),
        ),
    ]
