# Generated by Django 2.0 on 2020-11-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0169_auto_20201030_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreview',
            name='job_position',
        ),
        migrations.DeleteModel(
            name='JobReview',
        ),
    ]
