# Generated by Django 2.0 on 2020-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0172_data_migrate_prototype_public_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositionneed',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
    ]
