# Generated by Django 2.0 on 2020-12-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0172_data_migrate_prototype_public_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tests', to='projects.Project', verbose_name='项目')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tests', to=settings.AUTH_USER_MODEL, verbose_name='测试')),
            ],
            options={
                'verbose_name': '项目测试',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tests',
            field=models.ManyToManyField(related_name='tests_projects', through='projects.ProjectTest', to=settings.AUTH_USER_MODEL, verbose_name='测试工程师'),
        ),
    ]
