# Generated by Django 2.0 on 2020-12-29 11:15
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0173_jobpositionneed_canceled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpositionneed',
            old_name='expected_confirmation_time',
            new_name='expected_date',
        ),
        migrations.AlterField(
            model_name='jobpositionneed',
            name='expected_date',
            field=models.DateField(verbose_name='预计确认日期'),
        ),
    ]
