# Generated by Django 2.0 on 2021-01-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0173_auto_20201230_1212'),
        ('projects', '0174_auto_20201229_1115'),
    ]

    operations = [
    ]
