# Generated by Django 2.0 on 2021-01-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0176_data_migrate_project_test_to_project_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectclient',
            options={'ordering': ['created_at'], 'verbose_name': '项目客户'},
        ),
        migrations.AlterModelOptions(
            name='projecttest',
            options={'ordering': ['created_at'], 'verbose_name': '项目测试'},
        ),
    ]
