# Generated by Django 2.0 on 2021-01-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0177_auto_20210112_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bd_projects', to=settings.AUTH_USER_MODEL, verbose_name='BD'),
        ),
    ]
