# Generated by Django 2.2.14 on 2021-03-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0182_data_migrate_project_playbook_checkpoint_gantt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'verbose_name': '项目阶段'},
        ),
    ]
