# Generated by Django 2.2.14 on 2021-03-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0183_auto_20210313_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPayment',
        ),
    ]
