# Generated by Django 2.2.14 on 2021-04-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0185_auto_20210407_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_by', models.CharField(blank=True, choices=[('manager', '项目经理'), ('tpm', 'TPM'), ('designer', '设计'), ('test', '测试')], max_length=20, null=True, verbose_name='填写人')),
                ('engineer_type', models.CharField(blank=True, choices=[('developer', '开发'), ('test', '测试'), ('designer', '设计')], max_length=20, null=True, verbose_name='工程师类型')),
                ('version', models.FloatField(blank=True, default=1.0, max_length=10, null=True, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('online', '线上版本'), ('history', '历史版本')], max_length=20, verbose_name='发布状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问卷',
            },
        ),
        migrations.RemoveField(
            model_name='jobstandardscore',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='communication',
            field=models.FloatField(blank=True, null=True, verbose_name='交流沟通'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开发速度'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='execute',
            field=models.FloatField(blank=True, null=True, verbose_name='执行'),
        ),
        migrations.AlterField(
            model_name='jobstandardscore',
            name='quality',
            field=models.FloatField(blank=True, null=True, verbose_name='功能质量'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('communication', '沟通能力'), ('efficiency', '工作效率'), ('quality', '项目质量'), ('execute', '执行能力'), ('others', '其它')], default='others', max_length=20, verbose_name='题目类型')),
                ('title', models.CharField(max_length=200, verbose_name='题目')),
                ('index', models.IntegerField(default=0, verbose_name='在问卷中的顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.Questionnaire')),
            ],
            options={
                'verbose_name': '题目',
            },
        ),
        migrations.CreateModel(
            name='JobFinalScore',
            fields=[
                ('communication', models.FloatField(blank=True, null=True, verbose_name='交流沟通')),
                ('efficiency', models.FloatField(blank=True, null=True, verbose_name='开发速度')),
                ('quality', models.FloatField(blank=True, null=True, verbose_name='功能质量')),
                ('execute', models.FloatField(blank=True, null=True, verbose_name='执行')),
                ('job_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_final_scores', serialize=False, to='projects.JobPosition')),
                ('evaluate', models.TextField(blank=True, max_length=256, null=True, verbose_name='工程师评价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_final_scores', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
            options={
                'verbose_name': '工程师最终评分',
            },
        ),
        migrations.CreateModel(
            name='GradeQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_skip_grade', models.BooleanField(default=False, verbose_name='是否跳过评分')),
                ('remarks', models.TextField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_questionnaires', to='projects.JobPosition')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_questionnaires', to='projects.Questionnaire', verbose_name='问卷')),
                ('score_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
            ],
            options={
                'verbose_name': '工程师评分问卷',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=15, null=True, verbose_name='选项内容')),
                ('index', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='projects.Question')),
            ],
            options={
                'verbose_name': '题目选项',
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_sheets', to='projects.Choice')),
                ('grade_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='projects.GradeQuestionnaire')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='projects.Question')),
            ],
            options={
                'verbose_name': '评分问卷答卷',
            },
        ),
    ]
