# Generated by Django 2.2.14 on 2021-04-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0054_developer_real_name_auth_status_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0185_auto_20210407_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkHourPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('product_manager', '产品'), ('developer', '开发'), ('tpm', '技术项目经理'), ('test', '测试'), ('designer', '设计')], max_length=20, null=True, verbose_name='职位')),
                ('plan_consume_days', models.FloatField(blank=True, null=True, verbose_name='计划消耗')),
                ('elapsed_time', models.FloatField(blank=True, null=True, verbose_name='已耗时')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_work_hour_plans', to='developers.Developer', verbose_name='工程师')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_work_hour_plans', to='projects.Project', verbose_name='项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_work_hour_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目工时表',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkHourRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_start_date', models.DateField(verbose_name='统计开始日期')),
                ('statistic_end_date', models.DateField(verbose_name='统计结束日期')),
                ('week_consume_hours', models.FloatField(blank=True, null=True, verbose_name='周消耗')),
                ('predict_residue_days', models.FloatField(blank=True, null=True, verbose_name='预计剩余')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project_work_hour_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hour_records', to='projects.ProjectWorkHourPlan', verbose_name='项目工时计划')),
            ],
            options={
                'verbose_name': '项目工时记录表',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkHourOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑')], default='other', max_length=15, verbose_name='操作类型')),
                ('origin_plan_consume_days', models.FloatField(blank=True, null=True, verbose_name='原计划消耗')),
                ('new_plan_consume_days', models.FloatField(blank=True, null=True, verbose_name='新计划消耗')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hour_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project_work_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='projects.ProjectWorkHourPlan', verbose_name='项目工时')),
            ],
            options={
                'verbose_name': '项目工时操作记录',
            },
        ),
    ]
