# Generated by Django 2.2.14 on 2021-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0186_projectworkhouroperationlog_projectworkhourplan_workhourrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkhourplan',
            name='elapsed_time',
            field=models.FloatField(default=0, verbose_name='已耗时'),
        ),
    ]
