# Generated by Django 2.2.14 on 2021-04-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0186_auto_20210423_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobFinalScore',
        ),
    ]
