# Generated by Django 2.2.14 on 2021-04-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0187_delete_jobfinalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradequestionnaire',
            name='score_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='评分人'),
        ),
    ]
