# Generated by Django 2.2.14 on 2021-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0187_auto_20210416_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkhourplan',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', '项目经理'), ('product_manager', '产品'), ('developer', '开发'), ('tpm', '技术项目经理'), ('test', '测试'), ('designer', '设计')], max_length=20, null=True, verbose_name='职位'),
        ),
    ]
