# Generated by Django 2.2.14 on 2021-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0188_auto_20210423_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('online', '线上版本'), ('history', '历史版本')], default='draft', max_length=20, verbose_name='发布状态'),
        ),
    ]
