# Generated by Django 2.2.14 on 2021-04-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0188_auto_20210426_1828'),
        ('projects', '0189_auto_20210426_1608'),
    ]

    operations = [
    ]
