# Generated by Django 2.2.14 on 2021-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0190_merge_20210429_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
