# Generated by Django 2.2.14 on 2021-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_questionnaire_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreferencescore',
            name='communication',
            field=models.FloatField(blank=True, null=True, verbose_name='交流沟通'),
        ),
        migrations.AlterField(
            model_name='jobreferencescore',
            name='efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开发速度'),
        ),
        migrations.AlterField(
            model_name='jobreferencescore',
            name='execute',
            field=models.FloatField(blank=True, null=True, verbose_name='执行'),
        ),
        migrations.AlterField(
            model_name='jobreferencescore',
            name='quality',
            field=models.FloatField(blank=True, null=True, verbose_name='功能质量'),
        ),
    ]
