# Generated by Django 2.2.14 on 2021-05-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0192_auto_20210430_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='选项内容'),
        ),
    ]
