# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0025_data_init_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '记录'), (1, '进行打款'), (2, '完成打款'), (3, '异常/取消')], default=0, verbose_name='状态')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('bank_info', models.TextField(verbose_name='银行信息')),
                ('amount', models.FloatField(verbose_name='额度')),
                ('expected_at', models.DateField(verbose_name='期望日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.JobPosition', verbose_name='开发岗位')),
            ],
        ),
    ]
