# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-19 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpayment',
            options={'permissions': (('view_all_payments', 'Can view all payments'),)},
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='expected_at',
            field=models.DateField(default=datetime.date.today, verbose_name='期望日期'),
        ),
    ]
