# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_init_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpayment',
            options={'permissions': (('view_all_payments', 'Can view all payments'),), 'verbose_name': '打款记录'},
        ),
    ]
