# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20171128_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpayment',
            options={'permissions': (('gear_view_all_payments', '查看全部打款'),), 'verbose_name': '打款记录'},
        ),
    ]
