# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-16 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20180308_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpayment',
            options={'permissions': (('gear_view_all_developer_payments', '查看全部工程师打款'),), 'verbose_name': '打款记录'},
        ),
    ]
