# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-15 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0009_permission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启动时间'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
