# Generated by Django 2.0 on 2019-12-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20181115_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
