# Generated by Django 2.0 on 2020-11-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0169_auto_20201030_1423'),
        ('finance', '0011_jobpayment_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='合同名称')),
                ('capital_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款账户')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='总金额')),
                ('invoice', models.CharField(choices=[('general', '普票'), ('special', '专票'), ('not_required', '不需要'), ('required', '需要')], default='not_required', max_length=50, verbose_name='发票')),
                ('status', models.CharField(choices=[('process', '进行中'), ('completed', '正常完成'), ('termination', '异常终止')], default='process', max_length=50, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_payments', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目收款',
            },
        ),
        migrations.CreateModel(
            name='ProjectPaymentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='排序位置')),
                ('receivable_amount', models.FloatField(verbose_name='应收款')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='预计日期')),
                ('receipted_amount', models.FloatField(blank=True, null=True, verbose_name='已收款')),
                ('receipted_date', models.DateField(blank=True, null=True, verbose_name='收款日期')),
                ('invoice', models.CharField(choices=[('general', '普票'), ('special', '专票'), ('have', '有票'), ('none', '无票')], default='none', max_length=15, verbose_name='发票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='finance.ProjectPayment', verbose_name='项目收款')),
            ],
            options={
                'verbose_name': '项目收款阶段',
                'ordering': ['index'],
            },
        ),
    ]
