# Generated by Django 2.0 on 2020-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_projectpayment_projectpaymentstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymentstage',
            name='invoice',
            field=models.CharField(choices=[('general', '普票'), ('special', '专票'), ('have', '已开'), ('none', '未开')], default='none', max_length=15, verbose_name='发票'),
        ),
    ]
