# Generated by Django 2.0 on 2020-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20201105_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='close_reason',
            field=models.TextField(blank=True, null=True, verbose_name='终止原因'),
        ),
    ]
