# Generated by Django 2.0 on 2020-11-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20201106_1609'),
        ('finance', '0012_auto_20201111_1550'),
    ]

    operations = [
    ]
