# Generated by Django 2.0 on 2020-11-20 16:09

from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0170_auto_20201106_1609'),
        ('finance', '0018_merge_20201111_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=20, verbose_name='合同名字')),
                ('develop_date_start', models.DateField(verbose_name='开发周期开始日期')),
                ('develop_date_end', models.DateField(verbose_name='开发周期结束日期')),
                ('develop_days', models.IntegerField(verbose_name='开发天数')),
                ('contract_money', models.FloatField(verbose_name='合同金额')),
                ('develop_sprint', models.IntegerField(verbose_name='开发sprint数量')),
                ('remit_way', models.TextField(verbose_name='打款方式')),
                ('project_results_show', models.TextField(verbose_name='项目成果交付')),
                ('maintain_period', models.IntegerField(default=6, verbose_name='工程师维护周期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('uncommitted', '未提交'), ('waiting', '待签约'), ('signed', '已签约'), ('closed', '已关闭')], default='waiting', max_length=20, verbose_name='合同状态')),
                ('close_reason', models.TextField(blank=True, null=True, verbose_name='关闭原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='关闭日期')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('fadada', models.CharField(blank=True, max_length=30, null=True, verbose_name='法大大')),
                ('id_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('front_side_of_id_card', models.ImageField(blank=True, null=True, upload_to=finance.models.JobContract.generate_filename, verbose_name='身份证正面照')),
                ('back_side_of_id_card', models.ImageField(blank=True, null=True, upload_to=finance.models.JobContract.generate_filename, verbose_name='身份证反面照')),
                ('payee_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='收款人户名')),
                ('payee_id_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='收款人身份证号码')),
                ('payee_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='收款人手机号')),
                ('payee_opening_bank', models.CharField(blank=True, max_length=128, null=True, verbose_name='收款人开户行')),
                ('payee_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人收款账号')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_contracts', to='projects.JobPosition')),
            ],
            options={
                'verbose_name': '工程师合同',
            },
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payee_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人收款账号'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payee_id_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收款人身份证号码'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payee_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='收款人户名'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payee_opening_bank',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='收款人开户行'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payee_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收款人手机号'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='payment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='打款原因'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='job_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_payments', to='finance.JobContract', verbose_name='工程师合同'),
        ),
    ]
