# Generated by Django 2.0 on 2020-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='名称'),
        ),
    ]
