# Generated by Django 2.0 on 2020-11-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20201120_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcontract',
            options={'ordering': ['-created_at'], 'verbose_name': '工程师合同'},
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='status',
            field=models.CharField(choices=[('uncommitted', '未提交'), ('waiting', '待签约'), ('signed', '已签约'), ('closed', '已关闭')], default='uncommitted', max_length=20, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='bank_info',
            field=models.TextField(blank=True, null=True, verbose_name='银行信息'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='job_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.JobContract', verbose_name='工程师合同'),
        ),
    ]
