# Generated by Django 2.0 on 2020-11-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_publicfile'),
        ('finance', '0022_data_miarate_old_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='develop_function_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File', verbose_name='开发功能说明'),
        ),
    ]
