# Generated by Django 2.0 on 2020-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20201126_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='is_null_contract',
            field=models.BooleanField(default=False, verbose_name='是否是空合同'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭日期'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='payee_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人户名'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='sign_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签约日期'),
        ),
    ]
