# Generated by Django 2.0 on 2020-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_jobcontract_develop_function_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='payee_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人户名'),
        ),
    ]
