# Generated by Django 2.0 on 2020-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20201210_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='close_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='终止备注'),
        ),
    ]
