# Generated by Django 2.0 on 2020-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20201210_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='contract_money',
            field=models.IntegerField(verbose_name='合同金额'),
        ),
    ]
