# Generated by Django 2.0 on 2020-12-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20201215_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpayment',
            name='payee_opening_bank',
            field=models.TextField(blank=True, null=True, verbose_name='收款人开户行'),
        ),
    ]
