# Generated by Django 2.0 on 2021-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_data_migrate_old_job_position_contract_payee_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
    ]
