# Generated by Django 2.0 on 2021-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_jobcontract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='is_confidentiality_agreement',
            field=models.BooleanField(default=True, verbose_name='是否有保密协议'),
        ),
    ]
