# Generated by Django 2.2.14 on 2021-01-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_publicfile'),
        ('finance', '0035_data_migrate_old_job_position_confidentiality_agreement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='delivery_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_contracts', to='files.File', verbose_name='交付清单'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='global_design',
            field=models.DateField(blank=True, null=True, verbose_name='整体设计时间'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='pay_way',
            field=models.CharField(choices=[('disposable', '一次性支付'), ('grading', '分阶段支持')], default='grading', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='style_confirm',
            field=models.DateField(blank=True, null=True, verbose_name='风格确认时间'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='walk_through',
            field=models.DateField(blank=True, null=True, verbose_name='设计走查'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='develop_function_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_contracts', to='files.File', verbose_name='开发功能说明'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='develop_sprint',
            field=models.IntegerField(blank=True, null=True, verbose_name='开发sprint数量'),
        ),
    ]
