# Generated by Django 2.2.14 on 2021-02-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_auto_20210128_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='contract_name',
            field=models.CharField(max_length=100, verbose_name='合同名字'),
        ),
    ]
