# Generated by Django 2.2.14 on 2021-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_auto_20210201_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='contract_name',
            field=models.CharField(max_length=200, verbose_name='合同名字'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='pay_way',
            field=models.CharField(choices=[('one_off', '一次性支付'), ('installments', '分阶段支付')], default='installments', max_length=20, verbose_name='支付方式'),
        ),
    ]
