# Generated by Django 2.2.14 on 2021-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0039_data_migrate_contract_pay_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('contract_termination', '合同终止'), ('fill_error', '填写错误')], max_length=32, null=True, verbose_name='终止原因'),
        ),
    ]
