# Generated by Django 2.2.14 on 2021-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_auto_20210220_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='contract_sign_link',
            field=models.TextField(blank=True, null=True, verbose_name='主合同签署链接'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合同文件id'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='flow_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合同签署流程id'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='generate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成时间'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='is_esign_contract',
            field=models.BooleanField(default=True, verbose_name='是否是E签宝合同'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='is_sign_contract',
            field=models.BooleanField(default=False, verbose_name='是否已签署工程师合同'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='is_sign_secret',
            field=models.BooleanField(default=False, verbose_name='是否已签署保密协议'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='secret_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保密协议文件id'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='secret_flow_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='保密协议签署流程id'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='secret_sign_link',
            field=models.TextField(blank=True, null=True, verbose_name='保密协议签署链接'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='status',
            field=models.CharField(choices=[('uncommitted', '未提交'), ('un_generate', '待生成'), ('rejected', '已驳回'), ('waiting', '待签约'), ('signed', '已签约'), ('closed', '已关闭')], default='uncommitted', max_length=20, verbose_name='合同状态'),
        ),
    ]
