# Generated by Django 2.2.14 on 2021-04-01 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('developers', '0052_developer_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0042_data_migrate_contract_sign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcontract',
            old_name='sign_date',
            new_name='signed_at',
        ),
        migrations.RenameField(
            model_name='jobcontract',
            old_name='close_date',
            new_name='closed_at',
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签约时间'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='contract_category',
            field=models.CharField(choices=[('project', '项目合同'), ('regular', '固定合同')], default='project', max_length=25,
                                   verbose_name='合同类型'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='job_contracts', to='developers.Developer'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='principal_job_contracts', to=settings.AUTH_USER_MODEL,
                                    verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payments', to='developers.Developer'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='develop_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='开发天数'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='job_contracts', to='projects.JobPosition'),
        ),
        migrations.AlterField(
            model_name='jobcontract',
            name='remit_way',
            field=models.TextField(blank=True, null=True, verbose_name='打款方式'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='expected_at',
            field=models.DateField(verbose_name='期望日期'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payments', to='projects.JobPosition', verbose_name='开发岗位'),
        ),
    ]
