# Generated by Django 2.2.14 on 2021-04-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0044_data_migrate_job_contract_payment_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_job_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
