# Generated by Django 2.2.14 on 2021-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_jobcontract_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontract',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('ongoing', '进行中'), ('completed', '正常完成'), ('terminated', '异常终止')], max_length=50, null=True, verbose_name='打款状态'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='terminated_reason',
            field=models.CharField(blank=True, choices=[('terminated', '合同终止'), ('clerical_error', '填写错误')], max_length=32, null=True, verbose_name='终止原因'),
        ),
        migrations.AddField(
            model_name='jobcontract',
            name='terminated_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='终止备注'),
        ),
    ]
