# Generated by Django 2.0 on 2018-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20181118_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_sticky', 'created_at'], 'verbose_name': '评论'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
