# Generated by Django 2.0 on 2019-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20181203_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='内容文本'),
        ),
    ]
