# Generated by Django 2.0 on 2019-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_comment_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='codename',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='代号'),
        ),
    ]
