# Generated by Django 2.0 on 2020-06-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20200414_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='developers.Developer', verbose_name='评论工程师'),
        ),
    ]
