# Generated by Django 2.0 on 2020-07-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0003_auto_20200619_1302'),
        ('comments', '0012_auto_20200609_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='auth_top.TopUser', verbose_name='创建人'),
        ),
    ]
