# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-22 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0029_auto_20171207_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件人')),
                ('to', models.CharField(max_length=200, verbose_name='收件人')),
                ('cc', models.CharField(blank=True, max_length=200, null=True, verbose_name='抄送人')),
                ('bcc', models.CharField(blank=True, max_length=200, null=True, verbose_name='密送人')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件正文')),
                ('status', models.CharField(choices=[('0', '失败'), ('1', '成功'), ('2', '草稿')], default='2', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件正文')),
                ('cc', models.CharField(max_length=200, verbose_name='抄送人')),
            ],
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='gearmail.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
