# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='收件人'),
        ),
    ]
