# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0002_auto_20171226_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='cc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='抄送人'),
        ),
    ]
