# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0003_auto_20171226_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'permissions': (('gear_use_farm_send_email', '使用Farm发送邮件'),), 'verbose_name': '邮件记录'},
        ),
    ]
