# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0005_permission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '失败'), (1, '成功'), (2, '草稿')], default=2, max_length=1),
        ),
    ]
