# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0006_auto_20171229_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '失败'), (1, '成功'), (2, '草稿')], default=2),
        ),
    ]
