# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0007_auto_20180111_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮件标题'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='gearmail.EmailTemplate'),
        ),
    ]
