# Generated by Django 2.0 on 2020-05-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearmail', '0011_auto_20181118_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='模板名称'),
        ),
    ]
