# Generated by Django 2.0 on 2020-07-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='description_text',
            field=models.TextField(blank=True, null=True, verbose_name='描述文本'),
        ),
    ]
