# Generated by Django 2.0 on 2020-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_bug_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修复时间'),
        ),
    ]
