# Generated by Django 2.0 on 2020-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_bug_fixed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
