# Generated by Django 2.0 on 2020-09-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0004_auto_20200715_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑'), ('assign', '指派'), ('fix', '修复'), ('confirm', '确认修复'), ('close', '关闭'), ('reopen', '激活'), ('comment', '评论'), ('other', '操作')], default='other', max_length=15, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='testing.Bug', verbose_name='Bug')),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignee_bug_operation_logs', to='auth_top.TopUser', verbose_name='新分配人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_operation_logs', to='auth_top.TopUser', verbose_name='操作人')),
                ('origin_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_assignee_bug_operation_logs', to='auth_top.TopUser', verbose_name='原分配人')),
            ],
            options={
                'verbose_name': 'Bug操作记录',
            },
        ),
    ]
