# Generated by Django 2.0 on 2020-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_data_migrate_bug_comments_to_bug_operation_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestcase',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序位置'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序位置'),
        ),
        migrations.AddField(
            model_name='testplancase',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序位置'),
        ),
    ]
