# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


def data_migrate_test_cases_index(apps, schema_editor):
    # 通过get_model获取的Model是当执行脚本时前数据库的model 不是代码中最新的model
    Project = apps.get_model("projects", "Project")
    ProjectTestCaseModule = apps.get_model("testing", "ProjectTestCaseModule")
    TestCaseModule = apps.get_model("testing", "TestCaseModule")
    TestCaseLibrary = apps.get_model("testing", "TestCaseLibrary")

    for project in Project.objects.all():
        project_modules = project.test_case_modules.all()
        for module in project_modules:
            for index, case in enumerate(module.test_cases.filter(is_active=True).order_by('created_at')):
                case.index = index + 1
                case.save()

    for project in TestCaseLibrary.objects.all():
        project_modules = project.modules.all()
        for module in project_modules:
            for index, case in enumerate(module.test_cases.filter(is_active=True).order_by('created_at')):
                case.index = index + 1
                case.save()


class Migration(migrations.Migration):
    dependencies = [
        ('testing', '0007_auto_20200930_1107'),
    ]

    operations = [
        migrations.RunPython(data_migrate_test_cases_index, migrations.RunPython.noop),
    ]
