# Generated by Django 2.0 on 2020-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_data_migrate_test_case_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestcasemodule',
            name='full_index',
            field=models.TextField(blank=True, null=True, verbose_name='full_index'),
        ),
        migrations.AddField(
            model_name='projecttestcasemodule',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='full_name'),
        ),
        migrations.AddField(
            model_name='testcasemodule',
            name='full_index',
            field=models.TextField(blank=True, null=True, verbose_name='full_index'),
        ),
        migrations.AddField(
            model_name='testcasemodule',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='full_name'),
        ),
        migrations.AddField(
            model_name='testplanmodule',
            name='full_index',
            field=models.TextField(blank=True, null=True, verbose_name='full_index'),
        ),
        migrations.AddField(
            model_name='testplanmodule',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='full_name'),
        ),
    ]
