# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


def data_migrate_test_module_full_index(apps, schema_editor):
    # 通过get_model获取的Model是当执行脚本时前数据库的model 不是代码中最新的model
    from testing.models import ProjectTestCaseModule, TestCaseModule, TestPlanModule

    for obj in ProjectTestCaseModule.objects.all():
        obj.full_index = obj.build_full_index()
        obj.full_name = obj.build_full_name()
        obj.save()

    for obj in TestCaseModule.objects.all():
        obj.full_index = obj.build_full_index()
        obj.full_name = obj.build_full_name()
        obj.save()

    for obj in TestPlanModule.objects.all():
        obj.full_index = obj.build_full_index()
        obj.full_name = obj.build_full_name()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('testing', '0009_auto_20201111_1550'),
    ]

    operations = [
        migrations.RunPython(data_migrate_test_module_full_index, migrations.RunPython.noop),
    ]
