# Generated by Django 2.0 on 2020-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_data_migrate_test_module_full_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestcase',
            name='execution_count',
            field=models.IntegerField(default=0),
        ),
    ]
