# Generated by Django 2.0 on 2020-12-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0012_data_migrate_projecttestcase_execution_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCaseReviewOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑'), ('approved', '通过'), ('rejected', '驳回'), ('other', '其它')], default='other', max_length=15, verbose_name='操作类型')),
                ('content_data', models.TextField(blank=True, null=True, verbose_name='内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_case_review_operation_logs', to='testing.ProjectTestCase', verbose_name='项目用例')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_case_review_operation_logs', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目用例评审与操作记录',
            },
        ),
        migrations.CreateModel(
            name='TestPlanCaseExecuteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_type', models.CharField(choices=[('pass', '通过'), ('failed', '失败'), ('create_bug', '创建bug'), ('relevance_bug', '关联bug')], max_length=20, verbose_name='执行类型')),
                ('executed_status', models.CharField(choices=[('pending', '未执行'), ('pass', '通过'), ('failed', '失败')], max_length=20, verbose_name='执行后状态')),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_case_execute_logs', to='testing.Bug', verbose_name='Bug')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_case_execute_logs', to='testing.ProjectTestCase', verbose_name='项目用例')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_case_execute_logs', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目用例执行记录',
            },
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='计划名称'),
        ),
        migrations.AddField(
            model_name='testplancaseexecutelog',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plan_case_execute_logs', to='testing.ProjectTestPlan', verbose_name='测试计划'),
        ),
        migrations.AddField(
            model_name='testplancaseexecutelog',
            name='plan_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_case_execute_logs', to='testing.TestPlanCase', verbose_name='用例执行'),
        ),
    ]
