# Generated by Django 2.0 on 2020-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_data_migrate_testplancase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplancase',
            name='status',
            field=models.CharField(choices=[('pending', '未执行'), ('pass', '通过'), ('failed', '失败')], default='pending', max_length=15, verbose_name='状态'),
        ),
    ]
