# Generated by Django 2.0 on 2020-12-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_auto_20201209_1849'),
        ('testing', '0013_auto_20201209_1914'),
    ]

    operations = [
    ]
