# Generated by Django 2.0 on 2020-12-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0014_auto_20201209_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDayStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_bugs', models.IntegerField(default=0, verbose_name='新增bug数')),
                ('closed_bugs', models.IntegerField(default=0, verbose_name='关闭BUG数')),
                ('created_cases', models.IntegerField(default=0, verbose_name='新增项目用例数')),
                ('executed_cases', models.IntegerField(default=0, verbose_name='执行用例次数')),
                ('projects_detail', models.TextField(default='[]', verbose_name='每个项目的数据详情')),
                ('date', models.DateField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_day_statistics', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '测试数据统计',
            },
        ),
        migrations.CreateModel(
            name='TestMonthStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_bugs', models.IntegerField(default=0, verbose_name='新增bug数')),
                ('closed_bugs', models.IntegerField(default=0, verbose_name='关闭BUG数')),
                ('created_cases', models.IntegerField(default=0, verbose_name='新增项目用例数')),
                ('executed_cases', models.IntegerField(default=0, verbose_name='执行用例次数')),
                ('projects_detail', models.TextField(default='[]', verbose_name='每个项目的数据详情')),
                ('month', models.CharField(max_length=20, verbose_name='月份')),
                ('month_first_day', models.DateField(verbose_name='本月第一天')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_month_statistics', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'bug与项目用例月统计',
            },
        ),
        migrations.AddField(
            model_name='testplancase',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AlterUniqueTogether(
            name='testmonthstatistic',
            unique_together={('operator', 'month_first_day')},
        ),
        migrations.AlterUniqueTogether(
            name='testdaystatistic',
            unique_together={('operator', 'date')},
        ),
    ]
