# Generated by Django 2.0 on 2020-12-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_merge_20201209_1948'),
        ('testing', '0015_auto_20201210_1205'),
    ]

    operations = [
    ]
