# Generated by Django 2.0 on 2020-12-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_merge_20201210_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplancaseexecutelog',
            old_name='execute_at',
            new_name='executed_at',
        ),
        migrations.AlterField(
            model_name='projectcasereviewoperationlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to='testing.ProjectTestCase', verbose_name='项目用例'),
        ),
        migrations.AlterField(
            model_name='testplancaseexecutelog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_logs', to='testing.ProjectTestCase', verbose_name='项目用例'),
        ),
        migrations.AlterField(
            model_name='testplancaseexecutelog',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_executed_logs', to='testing.ProjectTestPlan', verbose_name='测试计划'),
        ),
    ]
