# Generated by Django 2.0 on 2020-12-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0017_auto_20201210_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTestCaseReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑'), ('approved', '通过'), ('rejected', '驳回'), ('other', '其它')], default='other', max_length=15, verbose_name='操作类型')),
                ('content_data', models.TextField(blank=True, null=True, verbose_name='内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to='testing.ProjectTestCase', verbose_name='项目用例')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_test_case_review_logs', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目用例评审记录',
            },
        ),
        migrations.CreateModel(
            name='TestCaseReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('edit', '编辑'), ('pending', '待评审'), ('approved', '通过'), ('rejected', '驳回'), ('other', '其它')], default='other', max_length=15, verbose_name='操作类型')),
                ('content_data', models.TextField(blank=True, null=True, verbose_name='内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to='testing.TestCase', verbose_name='项目用例')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_review_logs', to='auth_top.TopUser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '用例评审记录',
            },
        ),
        migrations.RenameModel(
            old_name='TestPlanCaseExecuteLog',
            new_name='ProjectTestCaseExecuteLog',
        ),
        migrations.RemoveField(
            model_name='projectcasereviewoperationlog',
            name='case',
        ),
        migrations.RemoveField(
            model_name='projectcasereviewoperationlog',
            name='operator',
        ),
        migrations.DeleteModel(
            name='ProjectCaseReviewOperationLog',
        ),
    ]
