# Generated by Django 2.0 on 2020-12-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_auto_20201214_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttestcaseexecutelog',
            name='plan_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_logs', to='testing.TestPlanCase', verbose_name='用例执行'),
        ),
    ]
