# Generated by Django 2.0 on 2021-01-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0174_auto_20201229_1115'),
        ('testing', '0019_auto_20201215_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDayBugStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugs_detail', models.TextField(default='{}', verbose_name='待修复bug数优先级统计数据')),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_bugs_statistic', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '测试数据统计',
            },
        ),
        migrations.AlterUniqueTogether(
            name='testdaybugstatistic',
            unique_together={('project', 'date')},
        ),
    ]
