# Generated by Django 2.2.14 on 2021-02-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0021_auto_20210109_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttestcase',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='testing.ProjectTestCaseModule', verbose_name='模块'),
        ),
    ]
