# Generated by Django 2.2.14 on 2021-02-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0022_auto_20210201_2344'),
        ('testing', '0022_auto_20210203_0030'),
    ]

    operations = [
    ]
