# Generated by Django 2.2.14 on 2021-02-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0023_merge_20210203_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='激活时间'),
        ),
        migrations.AddField(
            model_name='bug',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_bugs', to='auth_top.TopUser', verbose_name='激活人'),
        ),
    ]
