# Generated by Django 2.2.14 on 2021-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_auto_20210208_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaselibrary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
