# Generated by Django 2.2.14 on 2021-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('testing', '0025_auto_20210330_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestcase',
            name='case_type',
            field=models.CharField(choices=[('smoking', '冒烟用例'), ('no_smoking', '非冒烟用例')], default='no_smoking', max_length=20, verbose_name='用例类型'),
        ),
        migrations.AddField(
            model_name='projecttestcase',
            name='flow_type',
            field=models.CharField(choices=[('main_process', '主流程用例'), ('others', '其他类型用例')], default='others', max_length=20, verbose_name='流程类型'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='case_tags',
            field=models.ManyToManyField(related_name='project_test_plans', to='testing.ProjectTag', verbose_name='用例标签'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='execute_count',
            field=models.IntegerField(blank=True, choices=[(0, 'O次'), (1, '1次'), (2, '2次'), (3, '3次以上')], null=True, verbose_name='执行次数'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='executors',
            field=models.ManyToManyField(related_name='executor_project_test_plans', to='auth_top.TopUser', verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计测试结束时间'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='expected_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计测试开始时间'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='module_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='所选模块数'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='practical_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际测试开始时间'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='project_module_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目模块数'),
        ),
        migrations.AddField(
            model_name='projecttestplan',
            name='test_type',
            field=models.CharField(choices=[('full_volume', '全量测试'), ('smoking', '冒烟测试'), ('main_process', '主流程测试')], default='full_volume', max_length=20, verbose_name='测试类型'),
        ),
        migrations.AddField(
            model_name='testplancase',
            name='case_type',
            field=models.CharField(choices=[('smoking', '冒烟用例'), ('no_smoking', '非冒烟用例')], default='no_smoking', max_length=20, verbose_name='用例类型'),
        ),
        migrations.AddField(
            model_name='testplancase',
            name='flow_type',
            field=models.CharField(choices=[('main_process', '主流程用例'), ('others', '其他类型用例')], default='others', max_length=20, verbose_name='流程类型'),
        ),
        migrations.AlterField(
            model_name='projecttestplan',
            name='status',
            field=models.CharField(choices=[('not_start', '未开始'), ('ongoing', '进行中'), ('done', '已完成')], default='not_start', max_length=15, verbose_name='状态'),
        ),
    ]
