# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qq', models.CharField(blank=True, max_length=10, null=True)),
                ('wechat', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
