# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='描述')),
                ('submitter_comments', models.TextField(blank=True, null=True, verbose_name='提交人备注')),
                ('pm_comments', models.TextField(blank=True, null=True, verbose_name='产品经理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='接单时间')),
                ('contact_at', models.DateTimeField(blank=True, null=True, verbose_name='联系时间')),
                ('report_at', models.DateTimeField(blank=True, null=True, verbose_name='报告时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='潜在客户', to=settings.AUTH_USER_MODEL, verbose_name='产品经理')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='提交的潜在客户', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
        ),
    ]
