# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_potentialclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='认领时间'),
        ),
    ]
