# Generated by Django 2.0 on 2018-11-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170118_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='潜在客户', to=settings.AUTH_USER_MODEL, verbose_name='产品经理'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='提交的潜在客户', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
