# Generated by Django 2.0 on 2019-03-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_auto_20181118_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.TextField(verbose_name='线索简介')),
                ('remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='线索备注')),
                ('status', models.CharField(choices=[('contact', '前期沟通'), ('proposal', '进入需求'), ('no_deal', '未成单'), ('deal', '成单'), ('invalid', '无效关闭')], default='contact', max_length=10, verbose_name='线索状态')),
                ('reliability', models.CharField(choices=[('general', '普通'), ('major', '重点')], default='general', max_length=10, verbose_name='靠谱度')),
                ('source', models.CharField(choices=[('other', '其他'), ('search_engine', '搜索引擎'), ('client_referral', '客户/潜在客户推荐'), ('strategy_cooperation', '战略合作'), ('rebate_cooperation', '返点合作'), ('activity', '展会/活动')], max_length=25, verbose_name='需求来源')),
                ('other_source_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='其他来源备注')),
                ('activity_type', models.CharField(blank=True, choices=[('sponsor', '自办活动'), ('cosponsor', '协办活动'), ('participator', '参加活动')], max_length=15, null=True, verbose_name='来源活动类型')),
                ('activity_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='来源活动名称')),
                ('has_rebate', models.BooleanField(default=False, verbose_name='返点')),
                ('rebate_info', models.IntegerField(blank=True, null=True, verbose_name='返点信息')),
                ('company_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='公司名称')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人姓名')),
                ('contact_job', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人职位')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系方式')),
                ('closed_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='关闭备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '线索',
            },
        ),
        migrations.CreateModel(
            name='LeadIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_individuals', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '个人客户',
            },
        ),
        migrations.CreateModel(
            name='LeadOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_organizations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '组织客户',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.LeadIndividual', verbose_name='来源个人'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.LeadOrganization', verbose_name='来源组织'),
        ),
        migrations.AddField(
            model_name='lead',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to=settings.AUTH_USER_MODEL, verbose_name='销售'),
        ),
    ]
