# Generated by Django 2.0 on 2019-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190307_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('search_engine', '搜索引擎'), ('strategy_cooperation', '战略合作'), ('rebate_cooperation', '返点合作'), ('client_referral', '客户/潜在客户推荐'), ('activity', '展会/活动'), ('other', '其他')], max_length=25, verbose_name='需求来源'),
        ),
    ]
