# Generated by Django 2.0 on 2019-03-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20190313_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rebate_info',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='返点信息'),
        ),
    ]
