# Generated by Django 2.0 on 2019-03-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_data_migrate_lead_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='other_source_remarks',
            new_name='source_remark',
        ),
    ]
