# Generated by Django 2.0 on 2019-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20190320_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='线索备注'),
        ),
    ]
