# Generated by Django 2.0 on 2019-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20190417_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='search_engine_type',
            field=models.CharField(blank=True, choices=[('baidu', '百度SEM'), ('phone', '400电话'), ('website', '官网'), ('mini_program', '微信小程序')], max_length=15, null=True, verbose_name='搜索引擎类型'),
        ),
    ]
