# Generated by Django 2.0 on 2019-05-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_lead_search_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='proposal_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='需求关闭时间'),
        ),
        migrations.AddField(
            model_name='lead',
            name='proposal_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进入需求时间'),
        ),
    ]
