# Generated by Django 2.0 on 2019-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_data_migrate_lead_proposal_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
