# Generated by Django 2.0 on 2019-08-08 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0017_auto_20190702_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='需求名称')),
                ('client_background', models.CharField(choices=[('0', '个人'), ('1', '初创团队'), ('2', '传统企业'), ('3', '大型/上市公司'), ('4', '互联网公司事业部')], max_length=2, verbose_name='客户背景')),
                ('client_background_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='客户背景备注')),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('0', '产品咨询'), ('1', '原型设计'), ('2', 'UI设计'), ('3', '前端开发'), ('4', '后端开发'), ('5', '运维服务')], max_length=11, verbose_name='服务内容')),
                ('service_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='服务内容备注')),
                ('reliability_factor', multiselectfield.db.fields.MultiSelectField(choices=[('0', '询价比价为主'), ('1', '朋友/客户推荐'), ('2', '原有产品二次开发'), ('3', '无其他因素')], max_length=7, verbose_name='靠谱度影响因素')),
                ('reliability_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='靠谱度影响因素备注')),
                ('business_objective', models.TextField(verbose_name='业务目标')),
                ('application_platform', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'iOS'), ('1', 'Android'), ('2', '小程序'), ('3', '管理后台'), ('4', 'PC端网页web'), ('5', '移动端/公共号H5'), ('6', '软硬件结合'), ('7', '其他')], max_length=15, verbose_name='应用平台')),
                ('platform_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='应用平台备注')),
                ('available_material', multiselectfield.db.fields.MultiSelectField(choices=[('0', '只有需求描述'), ('1', 'BP/PPT版介绍'), ('2', '功能列表/思维导图'), ('3', '原型'), ('4', '设计稿'), ('5', '已有产品名称/链接'), ('6', '已有产品截图'), ('7', '其他')], max_length=15, verbose_name='已有材料')),
                ('material_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='已有材料备注')),
                ('reference', models.CharField(choices=[('0', '参考全部'), ('1', '参考部分页面/流程'), ('2', '其他'), ('3', '无')], max_length=2, verbose_name='竞品参考')),
                ('reference_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='竞品参考备注')),
                ('case', models.CharField(blank=True, max_length=96, null=True, verbose_name='案例')),
                ('decision_factor', multiselectfield.db.fields.MultiSelectField(choices=[('0', '价格敏感'), ('1', '质量敏感'), ('2', '业务最终目标敏感')], max_length=5, verbose_name='决策因素')),
                ('rigid_requirement', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'UI视觉要求'), ('1', '代码语言要求'), ('2', '其他')], max_length=5, verbose_name='硬性要求')),
                ('rigid_requirement_remarks', models.CharField(blank=True, max_length=96, null=True, verbose_name='硬性要求备注')),
                ('budget', models.CharField(blank=True, max_length=64, null=True, verbose_name='预算范围')),
                ('period', models.CharField(blank=True, max_length=64, null=True, verbose_name='时间范围')),
                ('decision_period', models.CharField(blank=True, max_length=64, null=True, verbose_name='决策周期')),
                ('special_time_point', models.CharField(blank=True, max_length=64, null=True, verbose_name='特殊时间节点')),
                ('contact_name', models.CharField(max_length=30, verbose_name='联系人姓名')),
                ('contact_role', models.CharField(choices=[('0', '对接人'), ('1', '决策人'), ('2', '中间人')], max_length=2, verbose_name='联系人角色')),
                ('appeal_background_one', models.CharField(choices=[('0', '只收集信息向上级汇报'), ('1', '拥有一定决策能力')], max_length=2, verbose_name='诉求背景一')),
                ('appeal_background_two', models.CharField(choices=[('0', '懂产品技术，能力还行'), ('1', '不太懂，觉得自己懂'), ('2', '不懂，且知道自己不懂')], max_length=2, verbose_name='诉求背景二')),
                ('appeal_background_three', models.CharField(choices=[('0', '渠道介绍，需要分成'), ('1', '内部成员，但需要返点'), ('2', '不需要返点')], max_length=2, verbose_name='诉求背景三')),
                ('other_remarks', models.TextField(blank=True, null=True, verbose_name='其他说明')),
                ('other_decision_maker', models.CharField(blank=True, max_length=64, null=True, verbose_name='其他决策人')),
                ('communication_cost', multiselectfield.db.fields.MultiSelectField(choices=[('0', '易于沟通和说服'), ('1', '较强势'), ('2', '逻辑性强，条理清楚'), ('3', '逻辑混乱'), ('4', '抠细节，有些事儿')], max_length=9, verbose_name='沟通成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement', to='clients.Lead', verbose_name='线索')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requirements', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '客户需求信息',
            },
        ),
    ]
