# Generated by Django 2.0 on 2019-08-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0018_requirementinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPunchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', '电话'), ('meet', '会面')], max_length=5, verbose_name='联系方式')),
                ('contact_time', models.DateTimeField(verbose_name='联系时间')),
                ('remarks', models.TextField(verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_punch_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='clients.Lead', verbose_name='线索')),
            ],
            options={
                'verbose_name': '联系打卡记录',
            },
        ),
    ]
