# Generated by Django 2.0 on 2019-08-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20190827_1155'),
        ('clients', '0019_leadpunchrecord'),
    ]

    operations = [
    ]
