# Generated by Django 2.0 on 2019-10-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_merge_20190827_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=30, null=True, verbose_name='渠道')),
                ('media', models.CharField(blank=True, max_length=30, null=True, verbose_name='媒体')),
                ('account', models.CharField(blank=True, max_length=30, null=True, verbose_name='账户')),
                ('plan', models.CharField(blank=True, max_length=30, null=True, verbose_name='计划')),
                ('unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='单元')),
                ('keywords', models.CharField(blank=True, max_length=30, null=True, verbose_name='关键词')),
                ('device', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('track_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='跟踪码')),
                ('track_url', models.TextField(blank=True, null=True, verbose_name='跟踪URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '跟踪码',
            },
        ),
        migrations.CreateModel(
            name='TrackCodeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_path', models.TextField(blank=True, null=True, verbose_name='上传文件')),
                ('output_path', models.TextField(blank=True, null=True, verbose_name='导出文件')),
                ('filename', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '跟踪码文件',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='track_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='跟踪码'),
        ),
    ]
