# Generated by Django 2.0 on 2019-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_auto_20191030_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtrack',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='leadtrack',
            name='plan',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='计划'),
        ),
        migrations.AlterField(
            model_name='leadtrack',
            name='unit',
            field=models.TextField(blank=True, null=True, verbose_name='单元'),
        ),
    ]
