# Generated by Django 2.0 on 2019-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20191104_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtrack',
            name='md5_hash',
            field=models.TextField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
