# Generated by Django 2.0 on 2019-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_leadtrack_md5_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='leave_info_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户留资时间'),
        ),
    ]
