# Generated by Django 2.0 on 2019-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0024_lead_leave_info_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='leave_info_type',
            field=models.CharField(blank=True, choices=[('53kf', '53客服'), ('form_submit', '表单提交')], max_length=15,
                                   null=True, verbose_name='客户留资方式'),
        ),
    ]
