# Generated by Django 2.0 on 2020-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_lead_leave_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementinfo',
            name='rebate_proportion',
            field=models.IntegerField(blank=True, null=True, verbose_name='返点比例'),
        ),
    ]
