# Generated by Django 2.0 on 2020-01-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_requirementinfo_rebate_proportion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sem', 'SEM'), ('website', '官网（非SEM）'), ('content_marketing', '内容营销'), ('social_network', '社群/朋友圈/微信好友'), ('new_client', '客户新项目'), ('client_referral', '客户推荐'), ('activity', '活动'), ('startup_camp', '创业营/商学院/训练营'), ('org_referral', '企业/机构/协会推荐')], max_length=25, verbose_name='来源类型')),
                ('sem_type', models.CharField(blank=True, choices=[('sougou', '搜狗'), ('shenma', '神马'), ('360', '360'), ('baidu', '百度'), ('phone', '400电话'), ('toutiao', '今日头条')], max_length=25, null=True, verbose_name='SEM来源类型')),
                ('sem_track_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='SEM追踪码')),
                ('leave_info_type', models.CharField(blank=True, choices=[('53kf', '53客服'), ('form_submit', '表单提交')], max_length=15, null=True, verbose_name='客户留资方式')),
                ('leave_info_at', models.DateTimeField(blank=True, null=True, verbose_name='客户留资时间')),
                ('referer_url', models.TextField(blank=True, null=True, verbose_name='页面url')),
                ('track_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='追踪码（非SEM）')),
                ('content_marketing_type', models.CharField(blank=True, choices=[('wx_mp', '微信小程序'), ('wx_service', '微信服务号'), ('wx_sub', '微信订阅号'), ('other', '其他')], max_length=25, null=True, verbose_name='内容营销来源类型')),
                ('source_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='来源备注')),
                ('network_referrer_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='社交网络推荐人姓名')),
                ('network_referrer_organization', models.TextField(blank=True, null=True, verbose_name='社交网络推荐人工作单位')),
                ('network_referrer_contact_info', models.TextField(blank=True, null=True, verbose_name='社交网络推荐人联系方式')),
                ('activity_type', models.CharField(blank=True, choices=[('sponsor', '自办活动'), ('cosponsor', '协办活动'), ('participator', '参加活动')], max_length=15, null=True, verbose_name='来源活动类型')),
                ('activity_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='来源活动名称')),
                ('organization_type', models.CharField(blank=True, choices=[('云服务商', '云服务商'), ('SaaS服务商', 'SaaS服务商'), ('众包平台', '众包平台'), ('选型平台', '选型平台'), ('培训机构', '培训机构'), ('投资机构', '投资机构'), ('FA', 'FA'), ('行业协会', '行业协会'), ('众创空间', '众创空间'), ('孵化器', '孵化器'), ('公关营销公司', '公关营销公司'), ('咨询公司', '咨询公司'), ('设计公司', '设计公司'), ('友商竞品', '友商竞品'), ('代理商', '代理商'), ('集成商', '集成商'), ('行业媒体', '行业媒体'), ('其它', '其它')], max_length=20, null=True, verbose_name='机构/企业类型')),
                ('organization_contact_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='机构对接人姓名')),
                ('organization_contact_info', models.TextField(blank=True, null=True, verbose_name='机构对接人联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '线索来源',
            },
        ),
        migrations.AddField(
            model_name='leadorganization',
            name='organization_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='组织类型'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('search_engine', '搜索引擎'), ('strategy_cooperation', '战略合作'), ('rebate_cooperation', '返点合作'), ('client_referral', '客户/潜在客户推荐'), ('activity', '展会/活动'), ('other', '其他')], max_length=25, null=True, verbose_name='需求来源'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='track_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='跟踪码'),
        ),
        migrations.AlterField(
            model_name='leadtrack',
            name='track_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='跟踪码'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources', to='clients.LeadOrganization', verbose_name='企业/组织/机构'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='clients.LeadSource', verbose_name='线索来源数据'),
        ),
    ]
