# Generated by Django 2.0 on 2020-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20200109_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='sem_type',
            field=models.CharField(blank=True, choices=[('sougou', '搜狗'), ('shenma', '神马'), ('360', '360'), ('baidu', '百度'), ('phone', '400电话'), ('toutiao', '今日头条'), ('other', '其他')], max_length=25, null=True, verbose_name='SEM来源类型'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='source_type',
            field=models.CharField(choices=[('sem', 'SEM'), ('website', '官网（非SEM）'), ('content_marketing', '内容营销'), ('social_network', '社群/朋友圈/微信好友'), ('client_project_iteration', '客户项目迭代'), ('client_new_project', '客户新项目'), ('client_referral', '客户推荐'), ('activity', '活动'), ('startup_camp', '创业营/商学院/训练营'), ('org_referral', '企业/机构/协会推荐'), ('other', '其他')], default='other', max_length=35, verbose_name='来源类型'),
        ),
    ]
