# Generated by Django 2.0 on 2020-01-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20200120_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsource',
            old_name='organization_contact_info',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='leadsource',
            old_name='organization_contact_name',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='leadsource',
            name='network_referrer_contact_info',
        ),
        migrations.RemoveField(
            model_name='leadsource',
            name='network_referrer_name',
        ),
        migrations.RemoveField(
            model_name='leadsource',
            name='network_referrer_organization',
        ),
    ]
