# Generated by Django 2.0 on 2020-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20200122_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='sem_project_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SEM产品分类'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='sem_search_term',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='SEM搜索词'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='source_address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='来源地区'),
        ),
    ]
