# Generated by Django 2.0 on 2020-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_auto_20200210_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='sem_project_category',
            field=models.TextField(blank=True, null=True, verbose_name='SEM产品分类'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='sem_search_term',
            field=models.TextField(blank=True, null=True, verbose_name='SEM搜索词'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='source_address',
            field=models.TextField(blank=True, null=True, verbose_name='来源地区'),
        ),
    ]
