# Generated by Django 2.0 on 2020-02-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0031_auto_20200211_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', '等待报价'), ('quoted', '已经报价')], default='waiting', max_length=15, verbose_name='状态')),
                ('company_name', models.TextField(blank=True, null=True, verbose_name='客户公司')),
                ('company_business', models.TextField(blank=True, null=True, verbose_name='公司业务')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('product_applications', models.TextField(blank=True, null=True, verbose_name='产品形态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('quotation_content', models.TextField(blank=True, null=True, verbose_name='报价内容')),
                ('quoted_at', models.DateTimeField(blank=True, null=True, verbose_name='报价时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.Lead', verbose_name='线索')),
                ('quoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_quotations', to=settings.AUTH_USER_MODEL, verbose_name='报价人')),
            ],
            options={
                'verbose_name': '线索报价',
                'ordering': ['-created_at'],
            },
        ),
    ]
