# Generated by Django 2.0 on 2020-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_leadquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquotation',
            name='calculator_link',
            field=models.TextField(blank=True, null=True, verbose_name='计算器链接'),
        ),
    ]
