# Generated by Django 2.0 on 2020-03-06 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0033_leadquotation_calculator_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquotation',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='产品信息编辑时间'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='edited_date',
            field=models.DateField(blank=True, null=True, verbose_name='产品信息编辑日期'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_quotations', to=settings.AUTH_USER_MODEL, verbose_name='最近编辑人'),
        ),
    ]
