# Generated by Django 2.0 on 2020-03-30 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0036_leadpunchrecord_contact_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquotation',
            name='quotation_list',
            field=models.TextField(blank=True, null=True, verbose_name='报价信息'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='驳回时间'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='rejecter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_quotations', to=settings.AUTH_USER_MODEL, verbose_name='驳回人'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='rejecter_reason',
            field=models.TextField(blank=True, null=True, verbose_name='驳回理由'),
        ),
        migrations.AlterField(
            model_name='leadquotation',
            name='status',
            field=models.CharField(choices=[('waiting', '等待报价'), ('rejected', '已驳回'), ('quoted', '已经报价')], default='waiting', max_length=15, verbose_name='状态'),
        ),
    ]
