# Generated by Django 2.0 on 2020-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_auto_20200330_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='closed_reason',
            new_name='invalid_remarks',
        ),
        migrations.AddField(
            model_name='lead',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关闭理由'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contact', '前期沟通'), ('proposal', '进入需求'), ('no_deal', '未成单'), ('deal', '成单'), ('apply_close', '关闭审核'), ('invalid', '无效关闭')], default='contact', max_length=10, verbose_name='线索状态'),
        ),
    ]
