# Generated by Django 2.0 on 2020-03-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0038_auto_20200330_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apply_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请关闭时间'),
        ),
        migrations.AddField(
            model_name='lead',
            name='apply_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_closed_leads', to=settings.AUTH_USER_MODEL, verbose_name='申请关闭者'),
        ),
        migrations.AddField(
            model_name='lead',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_leads', to=settings.AUTH_USER_MODEL, verbose_name='关闭者'),
        ),
    ]
