# Generated by Django 2.0 on 2020-04-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_auto_20200330_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquotation',
            old_name='rejecter_reason',
            new_name='rejected_reason',
        ),
    ]
