# Generated by Django 2.0 on 2020-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_auto_20200402_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contact', '前期沟通'), ('proposal', '进入需求'), ('no_deal', '未成单'), ('deal', '成单'), ('apply_close', '关闭审核'), ('invalid', '无效关闭')], default='contact', max_length=15, verbose_name='线索状态'),
        ),
    ]
