# Generated by Django 2.0 on 2020-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_auto_20200410_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='track_code',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='追踪码（非SEM）'),
        ),
    ]
