# Generated by Django 2.0 on 2020-05-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_clientinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leave_info_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leave_info_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='search_engine_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source_remark',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='track_code',
        ),
    ]
