# Generated by Django 2.0 on 2020-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_auto_20200506_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='company_link',
            field=models.TextField(blank=True, null=True, verbose_name='公司相关链接'),
        ),
    ]
