# Generated by Django 2.0 on 2020-05-07 18:33

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0045_clientinfo_company_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clients.models.LeadReportFile.generate_filename)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('is_active', models.BooleanField(default=True, verbose_name='可见状态')),
                ('author', models.CharField(blank=True, max_length=15, null=True, verbose_name='制作人')),
                ('is_public', models.BooleanField(default=True, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_lead_report_files', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to='clients.Lead', verbose_name='线索')),
            ],
            options={
                'verbose_name': '线索报告文件',
                'ordering': ['-published_at'],
            },
        ),
    ]
