# Generated by Django 2.0 on 2020-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_leadreportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='公司简介'),
        ),
    ]
