# Generated by Django 2.0 on 2020-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_auto_20200507_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rebate_proportion',
            field=models.IntegerField(blank=True, null=True, verbose_name='返点百分比例'),
        ),
    ]
