# Generated by Django 2.0 on 2020-05-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0058_proposal_decision_email'),
        ('clients', '0048_lead_rebate_proportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_info', to='proposals.Proposal', verbose_name='需求'),
        ),
    ]
