# Generated by Django 2.0 on 2020-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_clientinfo_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='rebate_info',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='返点信息'),
        ),
    ]
