# Generated by Django 2.0 on 2020-05-07 16:25

from django.db import migrations, models


def data_migrate_client_info_rebate_proportion_to_rebate_info(apps, schema_editor):
    pass
    # ClientInfo = apps.get_model("clients", "ClientInfo")
    #
    # items = ClientInfo.objects.all()
    # for item in items:
    #     if item.rebate in ['0', '1'] and item.rebate_proportion:
    #         item.rebate_info = str(int(item.rebate_proportion)) + '%'
    #         item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0059_data_migrate_leads_requirement_to_client_infos_proposals'),
        ('clients', '0050_clientinfo_rebate_info'),
    ]

    operations = [
        migrations.RunPython(data_migrate_client_info_rebate_proportion_to_rebate_info, migrations.RunPython.noop),
    ]
