# Generated by Django 2.0 on 2020-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_data_migrate_client_info_rebate_proportion_to_rebate_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='rebate',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='rebate_info',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='rebate_proportion',
        ),
    ]
