# Generated by Django 2.0 on 2020-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_auto_20200518_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='sem_type',
            field=models.CharField(blank=True, choices=[('sougou', '搜狗'), ('shenma', '神马'), ('360', '360'), ('baidu', '百度'), ('google', '谷歌'), ('phone', '400电话'), ('toutiao', '今日头条'), ('other', '其他')], max_length=25, null=True, verbose_name='SEM来源类型'),
        ),
    ]
