# Generated by Django 2.0 on 2020-08-05 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0053_auto_20200805_1035'),
        ('projects', '0159_auto_20200805_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='potentialclient',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='potentialclient',
            name='submitter',
        ),
        migrations.DeleteModel(
            name='PotentialClient',
        ),
    ]
