# Generated by Django 2.0 on 2020-08-05 14:36

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0003_auto_20200619_1302'),
        ('clients', '0054_auto_20200805_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('username', models.CharField(max_length=50, verbose_name='名称')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=clients.models.Client.generate_filename, verbose_name='头像')),
                ('avatar_color', models.CharField(blank=True, choices=[('#212736', 'Black'), ('#2161FD', 'Blue'), ('#36B37E', 'Green'), ('#F5121D', 'Red'), ('#FE802F', 'Orange'), ('#9254DE', 'Purple'), ('#EB2F96', 'Magenta')], max_length=10, null=True, verbose_name='头像颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='auth_top.TopUser', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目客户',
            },
        ),
    ]
