# Generated by Django 2.2.14 on 2021-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_auto_20210119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquotation',
            name='development_goal',
            field=models.TextField(blank=True, null=True, verbose_name='开发目标'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='integrity_require',
            field=models.CharField(blank=True, choices=[('mvp', 'MVP'), ('ripe_product', '成熟产品')], max_length=20, null=True, verbose_name='完整度要求'),
        ),
    ]
