# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 14:56
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def migrate_potential_clients(apps, schema_editor):


    PotentialClient = apps.get_model("clients", "PotentialClient")
    Proposal = apps.get_model("proposals", "Proposal")
    Comment = apps.get_model("comments", "Comment")
    ContentType.objects.get_for_model(Proposal)
    proposal_type = ContentType.objects.get(app_label="proposals", model="proposal")


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
        ('clients', '0003_auto_20170118_1728'),
    ]

    operations = [
        migrations.RunPython(migrate_potential_clients, migrations.RunPython.noop),
    ]
