# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 21:26
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import Q


def migrate_projects(apps, schema_editor):
    pass
    # Project = apps.get_model("projects", "Project")
    # Proposal = apps.get_model("proposals", "Proposal")
    # # Task = apps.get_model("projects", "Task")
    # Comment = apps.get_model("comments", "Comment")
    # proposal_type = ContentType.objects.get(app_label="proposals", model="proposal")
    # for project in Project.objects.filter(Q(status__lte=4) | Q(status=11)).all():
    #     proposal = Proposal()
    #     proposal.submitter_id = project.manager_id
    #     proposal.pm_id = project.manager_id
    #     proposal.description = project.name + project.desc
    #
    #     proposal.created_at = project.created_at
    #     proposal.assigned_at = project.created_at
    #
    #     if project.status <= 2:
    #         proposal.status = 2
    #     elif project.status == 3:
    #         proposal.status = 3
    #         proposal.contact_at = project.modified_at
    #     elif project.status == 4:
    #         proposal.status = 4
    #         proposal.contact_at = project.modified_at
    #         proposal.report_at = project.modified_at
    #     elif project.status == 11:
    #         proposal.status = 6
    #         proposal.closed_at = project.modified_at
    #
    #     proposal.save()
    #
    #     for t in project.tasks.all():
    #         t.content_type_id = proposal_type.id
    #         t.object_id = proposal.id
    #         t.save()
    #
    #     for c in project.status_comments.all():
    #         comment = Comment(author_id=c.author_id, content=c.content, create_at=c.created_at)
    #         comment.content_type_id = proposal_type.id
    #         comment.object_id = proposal.id
    #         comment.save()
    #
    #     for l in project.logs.all():
    #         l.content_type_id = proposal_type.id
    #         l.object_id = proposal.id
    #         l.save()
    #
    #     project.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0003_auto_20170408_0335'),
    ]

    operations = [
        migrations.RunPython(migrate_projects, migrations.RunPython.noop),
    ]
