# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_data_migrate_incomplete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='projects.Project', verbose_name='项目'),
        ),
    ]
