# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170426_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='source',
            field=models.IntegerField(choices=[(1, '其他'), (2, '官网/搜索引擎'), (3, '口碑'), (4, '朋友介绍'), (5, '兄弟公司'), (6, '空间/孵化器')], default=1, verbose_name='需求来源'),
        ),
    ]
