# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20170612_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': (('view_playbook', 'Can see playbook'), ('view_calculator', 'Can see calculator'), ('view_finished_in_30_days', 'Can see finished proposal in 30 days'))},
        ),
    ]
