# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20170802_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': (('view_playbook', 'Can see playbook in proposals'), ('view_calculator', 'Can see calculator'), ('view_finished_in_30_days', 'Can see finished proposal in 30 days'), ('view_30_finished_proposals', 'Can see 30 finished proposals'), ('view_all_proposals', 'Can see all proposals'), ('view_all_in_90_days', 'Can see all proposals in 90 days'))},
        ),
    ]
