# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_data_create_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
