# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_proposal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='closed_reason_comment',
            field=models.TextField(blank=True, null=True, verbose_name='未成单理由文本'),
        ),
    ]
