# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_data_proposal_closed_reason_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='source',
            field=models.IntegerField(choices=[(1, '其他'), (2, '官网/搜索引擎'), (3, '（弃用）口碑'), (4, '朋友'), (5, '合作机构'), (6, '空间/孵化器'), (7, '展会/活动'), (8, '客户'), (9, '主动BD')], default=1, verbose_name='需求来源'),
        ),
    ]
