# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_auto_20171101_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': (('view_playbook', 'Can see playbook in proposals'), ('view_calculator', 'Can see calculator'), ('view_created_in_30_days', 'Can see all proposal created in 30 days'), ('view_30_finished_proposals', 'Can see 30 finished proposals'), ('view_all_proposals', 'Can see all proposals'), ('view_created_in_90_days', 'Can see all proposals created in 90 days')), 'verbose_name': '需求'},
        ),
    ]
