# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_auto_20171128_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': (('gear_view_all_proposals', '查看全部需求'), ('gear_view_ongoing_proposals', '查看进行中的需求'), ('gear_view_proposals_finished_in_90_days', '查看最近90天内结束的需求'), ('gear_view_calculator', '查看计算器'), ('gear_view_playbook', '查看需求playbook')), 'verbose_name': '需求'},
        ),
    ]
