# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0018_permission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='需求名称'),
        ),
    ]
