# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_auto_20180124_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reliability',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='靠谱度'),
        ),
    ]
