# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-17 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0020_proposal_reliability'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='bd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_proposals', to=settings.AUTH_USER_MODEL, verbose_name='BD'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='产品经理'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_proposals', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
