# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-04 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_auto_20180417_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='bd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bd_proposals', to=settings.AUTH_USER_MODEL, verbose_name='BD'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_proposals', to=settings.AUTH_USER_MODEL, verbose_name='产品经理'),
        ),
    ]
