# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_data_migrate_proposals_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='source',
            field=models.IntegerField(choices=[(1, '其他'), (2, '搜索引擎'), (3, '客户/潜在客户推荐'), (4, '客户复购'), (5, '战略合作'), (6, '返点合作'), (7, '展会/活动'), (9, '自己挖掘')], default=1, verbose_name='需求来源'),
        ),
    ]
