# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_auto_20181101_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='source_remark',
            field=models.CharField(default='', max_length=50, verbose_name='需求来源备注'),
        ),
    ]
