# Generated by Django 2.0 on 2019-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_auto_20181118_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.IntegerField(choices=[(1, '等待认领'), (2, '等待沟通'), (3, '等待报告'), (4, '进行中'), (5, '建立商机'), (6, '走合同'), (10, '成单'), (11, '未成单')], default=1, verbose_name='需求状态'),
        ),
    ]
