# Generated by Django 2.0 on 2019-02-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0030_data_migrate_all_proposals_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('plain', '增值税普票'), ('special', '增值税专票')], max_length=1, verbose_name='开票类型')),
                ('invoice_mode', models.CharField(choices=[('invoice_first', '先票后款'), ('payment_first', '先款后票')], max_length=1, verbose_name='开票方式')),
                ('invoice_period', models.CharField(choices=[('one-off', '所有款项金额统一开票'), ('periodic', '一期一开')], max_length=1, verbose_name='开票周期')),
                ('invoice_info', models.TextField(verbose_name='开票信息')),
                ('addressee_name', models.CharField(max_length=10, verbose_name='邮寄收件人姓名')),
                ('addressee_phone_number', models.CharField(max_length=20, verbose_name='邮寄收件人联系方式')),
                ('addressee_address', models.CharField(max_length=100, verbose_name='邮寄收件人地址')),
                ('has_referral_fee', models.BooleanField(default=False, verbose_name='介绍费')),
                ('referral_fee_rebate', models.IntegerField(blank=True, null=True, verbose_name='介绍费返点')),
                ('has_marketing_plan', models.BooleanField(default=False, verbose_name='项目市场安排')),
                ('maintenance_period', models.IntegerField(verbose_name='项目维护期/月')),
                ('need_op_service', models.BooleanField(default=False, verbose_name='运维服务')),
                ('op_period', models.IntegerField(blank=True, null=True, verbose_name='运维周期/月')),
                ('op_service_charge', models.IntegerField(blank=True, null=True, verbose_name='运维服务费')),
                ('op_invoice_mode', models.CharField(blank=True, choices=[('invoice_first', '先票后款'), ('payment_first', '先款后票')], max_length=1, null=True, verbose_name='运维开票方式')),
                ('op_payment_mode', models.CharField(blank=True, choices=[('monthly', '按月'), ('quarterly', '按季度'), ('yearly', '按年')], max_length=1, null=True, verbose_name='运维支付类型')),
                ('project_background', models.TextField(verbose_name='项目背景')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_receipt', to='proposals.Proposal', verbose_name='需求')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_handover_receipts', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '交接清单',
            },
        ),
    ]
