# Generated by Django 2.0 on 2019-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_auto_20190221_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverreceipt',
            name='marketing_plan_info',
            field=models.TextField(blank=True, null=True, verbose_name='市场安排信息'),
        ),
        migrations.AlterField(
            model_name='handoverreceipt',
            name='op_service_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='运维服务费总金额(元）'),
        ),
        migrations.AlterField(
            model_name='handoverreceipt',
            name='referral_fee_rebate',
            field=models.IntegerField(blank=True, null=True, verbose_name='介绍费返点总额(元）'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.IntegerField(choices=[(1, '等待认领'), (2, '等待沟通'), (3, '等待报告'), (4, '进行中'), (5, '建立商机'), (6, '成单交接'), (10, '成单'), (11, '未成单')], default=1, verbose_name='需求状态'),
        ),
    ]
