# Generated by Django 2.0 on 2019-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0035_auto_20190305_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='reliability',
            field=models.CharField(choices=[('low', '低'), ('general', '中'), ('major', '高')], default='general', max_length=15, verbose_name='靠谱度'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='source',
            field=models.CharField(choices=[('other', '其他'), ('search_engine', '搜索引擎'), ('client_referral', '客户/潜在客户推荐'), ('client_repurchase', '客户复购'), ('strategy_cooperation', '战略合作'), ('rebate_cooperation', '返点合作'), ('activity', '活动/展会'), ('oneself', '自己挖掘')], default='search_engine', max_length=30, verbose_name='需求来源'),
        ),
    ]
