# Generated by Django 2.0 on 2019-03-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190307_1840'),
        ('proposals', '0037_data_migrate_proposals_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='clients.Lead', verbose_name='线索'),
        ),
    ]
