# Generated by Django 2.0 on 2019-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_proposal_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='budget',
            field=models.FloatField(blank=True, null=True, verbose_name='预算 单位:元'),
        ),
    ]
