# Generated by Django 2.0 on 2019-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0039_auto_20190318_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='submitter_comments',
            new_name='remarks',
        ),
    ]
