# Generated by Django 2.0 on 2019-03-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20190320_1422'),
        ('proposals', '0040_auto_20190320_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='activity_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='来源活动名称'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('sponsor', '自办活动'), ('cosponsor', '协办活动'), ('participator', '参加活动')], max_length=15, null=True, verbose_name='来源活动类型'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposals', to='clients.LeadIndividual', verbose_name='来源个人'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposals', to='clients.LeadOrganization', verbose_name='来源组织'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reliability',
            field=models.CharField(choices=[('low', '低'), ('general', '普通'), ('major', '重点')], default='general', max_length=15, verbose_name='靠谱度'),
        ),
    ]
