# Generated by Django 2.0 on 2019-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0042_auto_20190326_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='closed_reason',
            field=models.IntegerField(blank=True, choices=[(1, '其它'), (2, '无响应'), (3, '暂时不做'), (4, '选择其它家'), (5, '无效需求（不靠谱）')], null=True, verbose_name='未成单原因'),
        ),
    ]
