# Generated by Django 2.0 on 2019-08-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_requirementinfo'),
        ('proposals', '0047_data_migrate_proposals_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='requirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='clients.RequirementInfo', verbose_name='需求对接信息'),
        ),
    ]
