# Generated by Django 2.0 on 2019-10-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_auto_20190827_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='quip_doc_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip沟通文档ID'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='quip_folder_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip文件夹ID'),
        ),
    ]
