# Generated by Django 2.0 on 2019-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0050_auto_20191009_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='quip_folder_type',
            field=models.CharField(choices=[('auto', '自动创建'), ('select', '选择'), ('no_need', '不需要')], default='no_need', max_length=30, verbose_name='Quip文件夹类别'),
        ),
    ]
