# Generated by Django 2.0 on 2020-01-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20200109_1828'),
        ('proposals', '0051_proposal_quip_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lead_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='clients.LeadSource', verbose_name='线索来源数据'),
        ),
    ]
