# Generated by Django 2.0 on 2020-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0052_proposal_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='budget_unit',
            field=models.CharField(blank=True, choices=[('元', '元'), ('万', '万')], default='元', max_length=2, null=True, verbose_name='预算 单位'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='budget',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='预算'),
        ),
    ]
