# Generated by Django 2.0 on 2020-05-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0053_auto_20200316_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('index', models.IntegerField(default=0, verbose_name='排序位置')),
            ],
            options={
                'verbose_name': '应用平台',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('index', models.IntegerField(default=0, verbose_name='排序位置')),
            ],
            options={
                'verbose_name': '行业类型',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=0, verbose_name='排序位置')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='proposals.ProductType', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '产品类型',
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('parent', 'name')},
        ),
    ]
