# Generated by Django 2.0 on 2020-05-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0055_migrate_data_reports_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='search_engine_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='source',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='source_remark',
        ),
    ]
