# Generated by Django 2.0 on 2020-05-06 19:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0056_auto_20200506_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='application_platforms',
            field=models.ManyToManyField(related_name='proposals', to='proposals.ApplicationPlatform', verbose_name='应用平台'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='available_material',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'BP/PPT版介绍'), ('2', '功能列表/思维导图'), ('3', '原型'), ('4', '设计稿'), ('5', '已有产品'), ('9', '其他')], max_length=11, null=True, verbose_name='需求资料'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='business_objective',
            field=models.TextField(blank=True, null=True, verbose_name='业务目标'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='industries',
            field=models.ManyToManyField(related_name='proposals', to='proposals.Industry', verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='material_remarks',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='需求资料备注'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='period',
            field=models.TextField(blank=True, null=True, verbose_name='时间规划'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reference',
            field=models.CharField(blank=True, choices=[('0', '参考全部'), ('1', '参考部分页面/流程'), ('2', '其他')], max_length=2, null=True, verbose_name='竞品参考'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reference_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='竞品参考备注'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rigid_requirement',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '代码规范和代码语言要求'), ('2', '价格上限'), ('3', '明确的上线时间'), ('9', '其他')], max_length=7, null=True, verbose_name='硬性要求'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rigid_requirement_remarks',
            field=models.CharField(blank=True, max_length=96, null=True, verbose_name='硬性要求备注'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(verbose_name='需求描述'),
        ),
    ]
