# Generated by Django 2.0 on 2020-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0057_auto_20200506_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='decision_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='决策层邮箱'),
        ),
    ]
