# Generated by Django 2.0 on 2020-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0059_data_migrate_leads_requirement_to_client_infos_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='material_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='需求资料备注'),
        ),
    ]
