# Generated by Django 2.0 on 2020-05-07 16:25

from django.db import migrations, models


def data_migrate_proposals_rebate(apps, schema_editor):
    RequirementInfo = apps.get_model("clients", "RequirementInfo")

    requirements = RequirementInfo.objects.all()
    for requirement in requirements:
        lead = requirement.lead
        proposal = getattr(lead, 'proposal', None)

        if proposal:
            proposal.rebate = requirement.appeal_background_three
            proposal.rebate_info = str(
                int(requirement.rebate_proportion)) + '%' if requirement.rebate_proportion else None
            proposal.save()


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0061_auto_20200518_1421'),
    ]

    operations = [
        migrations.RunPython(data_migrate_proposals_rebate, migrations.RunPython.noop),
    ]
