# Generated by Django 2.0 on 2020-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0062_data_migrate_proposals_rebate_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='closed_reason_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='未成单原因备注'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='closed_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='未成单原因'),
        ),
    ]
