# Generated by Django 2.0 on 2020-05-07 16:25

from django.db import migrations, models
from proposals.models import Proposal

PROPOSAL_STATUS_DICT = Proposal.PROPOSAL_STATUS_DICT


def data_migrate_proposals_closed_reason(apps, schema_editor):
    Proposal = apps.get_model("proposals", "Proposal")

    no_deal_proposals = Proposal.objects.filter(status=PROPOSAL_STATUS_DICT['no_deal']['status'])
    for proposal in no_deal_proposals:
        proposal.closed_reason_remarks = proposal.closed_reason_comment
        proposal.closed_reason_text = proposal.get_closed_reason_display()
        proposal.save()


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0063_auto_20200601_1446'),
    ]

    operations = [
        migrations.RunPython(data_migrate_proposals_closed_reason, migrations.RunPython.noop),
    ]
