# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0006_auto_20170612_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('uid', models.CharField(default='uuid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25)),
                ('title', models.CharField(default='title', max_length=25)),
                ('version', models.CharField(default='v1.0', max_length=10)),
                ('author', models.CharField(default='author', max_length=15)),
                ('date', models.CharField(default='date', max_length=25)),
                ('markdown', models.TextField()),
                ('html', models.TextField()),
                ('user_visible', models.BooleanField(default=True)),
                ('show_next', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='proposals.Proposal', verbose_name='需求')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
