# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_migrate_gearhome_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
