# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-01 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170727_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at', 'title']},
        ),
    ]
