# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-10 16:52
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('reports', '0005_auto_20171101_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
