# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20180117_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='industry_classifications',
            field=models.ManyToManyField(related_name='reports', to='reports.IndustryClassification', verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='report',
            name='technology_types',
            field=models.ManyToManyField(related_name='reports', to='reports.TechnologyType', verbose_name='类型'),
        ),
    ]
