# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20180327_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default='', verbose_name='描述'),
        ),
    ]
