# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_add_industry_classification_technology_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='proposals.Proposal', verbose_name='需求'),
        ),
    ]
