# Generated by Django 2.0 on 2019-04-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0016_auto_20180411_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Grade',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '报告评分'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='rate',
            field=models.IntegerField(verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades',
                                    to='reports.Report', verbose_name='报告'),
        ),
    ]
