# Generated by Django 2.0 on 2019-04-30 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0017_auto_20190430_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('file', models.ImageField(upload_to=reports.models.FrameDiagram.generate_filename)),
                ('filename', models.CharField(max_length=128, verbose_name='文件名称')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='后缀')),
                ('file_url', models.TextField(blank=True, null=True, verbose_name='文件地址')),
                ('is_standard', models.BooleanField(default=False, verbose_name='标准框架图')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_diagrams', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '框架图',
            },
        ),
        migrations.CreateModel(
            name='FrameDiagramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '框架图标签',
            },
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('file', models.FileField(upload_to=reports.models.MindMap.generate_filename)),
                ('filename', models.CharField(max_length=128, verbose_name='文件名称')),
                ('file_url', models.TextField(blank=True, null=True, verbose_name='文件地址')),
                ('json_url', models.TextField(blank=True, null=True, verbose_name='json文件地址')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='image文件地址')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mind_maps', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '脑图',
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('file', models.FileField(upload_to=reports.models.ReportFile.generate_filename)),
                ('filename', models.CharField(max_length=128, verbose_name='文件名称')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='后缀')),
                ('file_url', models.TextField(blank=True, null=True, verbose_name='文件地址')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '报告文件',
            },
        ),
        migrations.AddField(
            model_name='framediagram',
            name='tags',
            field=models.ManyToManyField(related_name='frame_diagrams', to='reports.FrameDiagramTag', verbose_name='类型'),
        ),
    ]
