# Generated by Django 2.0 on 2019-05-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0018_auto_20190430_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '报告评论点',
            },
        ),
        migrations.CreateModel(
            name='QuotationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='报价估算')),
                ('period', models.CharField(blank=True, max_length=50, null=True, verbose_name='预计工期')),
                ('projects', models.CharField(blank=True, max_length=150, null=True, verbose_name='项目包含')),
                ('services', models.CharField(blank=True, max_length=150, null=True, verbose_name='服务范围')),
                ('price_detail', models.TextField(blank=True, null=True, verbose_name='报价详情')),
            ],
            options={
                'verbose_name': '项目报价方案',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='creation_source',
            field=models.CharField(choices=[('quip_link', 'Quip链接'), ('markdown', 'markdown文本'), ('farm', 'Farm')], default='quip_link', max_length=20, verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='report',
            name='main_content',
            field=models.TextField(blank=True, null=True, verbose_name='主要内容'),
        ),
        migrations.AddField(
            model_name='report',
            name='main_content_html',
            field=models.TextField(blank=True, null=True, verbose_name='主要内容html'),
        ),
        migrations.AddField(
            model_name='report',
            name='show_plan',
            field=models.BooleanField(default=True, verbose_name='显示报价方案'),
        ),
        migrations.AddField(
            model_name='report',
            name='version_content',
            field=models.TextField(blank=True, null=True, verbose_name='版本历史'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='制作人'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='制作日期'),
        ),
        migrations.AlterField(
            model_name='report',
            name='html',
            field=models.TextField(verbose_name='html内容'),
        ),
        migrations.AlterField(
            model_name='report',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='report',
            name='markdown',
            field=models.TextField(verbose_name='markdown内容'),
        ),
        migrations.AlterField(
            model_name='report',
            name='show_next',
            field=models.BooleanField(default=True, verbose_name='显示下一步'),
        ),
        migrations.AlterField(
            model_name='report',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='显示服务范围'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.CharField(max_length=30, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='report',
            name='version',
            field=models.CharField(default='v1.0', max_length=10, verbose_name='当前版本'),
        ),
        migrations.AddField(
            model_name='quotationplan',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_plans', to='reports.Report', verbose_name='报告'),
        ),
        migrations.AddField(
            model_name='commentpoint',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_points', to='reports.Report', verbose_name='局部评论点'),
        ),
    ]
