# Generated by Django 2.0 on 2019-05-19 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0020_migration_report_creation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_data', models.TextField(blank=True, null=True, verbose_name='内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '报告操作记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.TextField(blank=True, null=True, verbose_name='报告数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('number', models.IntegerField(default=1, verbose_name='编号')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_histories', to=settings.AUTH_USER_MODEL, verbose_name='制作人')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '历史版本',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edit_reports', to=settings.AUTH_USER_MODEL, verbose_name='最近编辑人'),
        ),
        migrations.AddField(
            model_name='report',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='revisionhistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reports.Report', verbose_name='报告'),
        ),
        migrations.AddField(
            model_name='operatingrecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_logs', to='reports.Report', verbose_name='报告'),
        ),
    ]
