# Generated by Django 2.0 on 2019-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20190519_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=10, null=True, verbose_name='当前版本'),
        ),
    ]
