# Generated by Django 2.0 on 2019-05-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_auto_20190520_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='show_next',
            field=models.BooleanField(default=True, verbose_name='下一步'),
        ),
        migrations.AlterField(
            model_name='report',
            name='show_plan',
            field=models.BooleanField(default=True, verbose_name='报价方案'),
        ),
        migrations.AlterField(
            model_name='report',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='服务范围'),
        ),
        migrations.AlterField(
            model_name='report',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
