# Generated by Django 2.0 on 2019-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0023_auto_20190522_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='quotationplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
