# Generated by Django 2.0 on 2019-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20190522_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='main_content_text',
            field=models.TextField(blank=True, null=True, verbose_name='主要内容文本'),
        ),
    ]
