# Generated by Django 2.0 on 2019-07-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_migration_frame_diagrams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryclassification',
            options={'verbose_name': '报告行业'},
        ),
        migrations.AlterModelOptions(
            name='technologytype',
            options={'verbose_name': '报告类型'},
        ),
    ]
