# Generated by Django 2.0 on 2019-07-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_auto_20190702_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationplan',
            options={'ordering': ['created_at'], 'verbose_name': '项目报价方案'},
        ),
    ]
