# Generated by Django 2.0 on 2019-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20190705_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framediagram',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
    ]
