# Generated by Django 2.0 on 2019-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20190920_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationplan',
            name='position',
            field=models.IntegerField(default=0, verbose_name='报价方案编号'),
        ),
    ]
