# Generated by Django 2.0 on 2019-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_auto_20191017_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='meeting_time',
            field=models.DateField(blank=True, null=True, verbose_name='会议时间'),
        ),
    ]
