# Generated by Django 2.0 on 2019-12-04 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0034_auto_20191204_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='publish_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_publish_reports', to=settings.AUTH_USER_MODEL, verbose_name='发布申请人'),
        ),
        migrations.AddField(
            model_name='report',
            name='publish_applicant_comment',
            field=models.TextField(blank=True, null=True, verbose_name='发布申请备注'),
        ),
    ]
