# Generated by Django 2.0 on 2019-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_auto_20191204_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='可见状态'),
        ),
    ]
