# Generated by Django 2.0 on 2020-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_report_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='publish_applicant_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请审核时间'),
        ),
    ]
