# Generated by Django 2.0 on 2020-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_report_publish_applicant_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='report',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='html内容'),
        ),
        migrations.AlterField(
            model_name='report',
            name='markdown',
            field=models.TextField(blank=True, null=True, verbose_name='markdown内容'),
        ),
    ]
