# Generated by Django 2.0 on 2020-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0054_auto_20200506_1304'),
        ('reports', '0038_auto_20200219_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='application_platforms',
            field=models.ManyToManyField(related_name='reports', to='proposals.ApplicationPlatform', verbose_name='应用平台'),
        ),
        migrations.AddField(
            model_name='report',
            name='industries',
            field=models.ManyToManyField(related_name='reports', to='proposals.Industry', verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='report',
            name='product_types',
            field=models.ManyToManyField(related_name='reports', to='proposals.ProductType', verbose_name='产品分类'),
        ),
    ]
