# Generated by Django 2.0 on 2020-05-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_auto_20200506_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tags',
        ),
    ]
