# Generated by Django 2.0 on 2020-07-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_migrate_reports_application_platforms_and_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='industry_classifications',
        ),
        migrations.RemoveField(
            model_name='report',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='report',
            name='technology_types',
        ),
        migrations.DeleteModel(
            name='IndustryClassification',
        ),
        migrations.DeleteModel(
            name='TechnologyType',
        ),
    ]
