# Generated by Django 2.2.14 on 2021-03-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_auto_20200715_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('helpful', '很有帮助'), ('not_helpful', '没有帮助')], max_length=20, verbose_name='评级')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器的身份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='reports.Report', verbose_name='报告')),
            ],
            options={
                'verbose_name': '报告评价',
            },
        ),
    ]
