# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 22:52
from __future__ import unicode_literals

from django.db import migrations
from farmbase.models import Profile
from django.contrib.auth.models import User


def create_profile(apps, schema_editor):
    users =  User.objects.all()
    for u in users:
        if not hasattr(u,'profile'):
            u.profile = Profile()
            u.save()

class Migration(migrations.Migration):
    dependencies = [
        ('farmbase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile, migrations.RunPython.noop),
    ]
