# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('farmbase', '0003_auto_20170207_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文档标题')),
                ('url', models.URLField(verbose_name='文档链接')),
                ('groups', models.ManyToManyField(related_name='documents', to='auth.Group', verbose_name='文档分组')),
            ],
        ),
    ]
