# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import farmbase.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0003_auto_20170207_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=farmbase.models.Profile.generate_filename, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_signature',
            field=models.TextField(blank=True, null=True, verbose_name='邮箱签名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
