# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-15 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0004_auto_20171213_1644'),
        ('farmbase', '0004_documents'),
    ]

    operations = [
    ]
