# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-11 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('farmbase', '0005_merge_20171215_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('codename', models.CharField(max_length=50, unique=True, verbose_name='codename')),
            ],
            options={
                'verbose_name': '功能模块',
            },
        ),
        migrations.CreateModel(
            name='FunctionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='codename')),
                ('groups', models.ManyToManyField(related_name='func_perms', to='auth.Group', verbose_name='用户组')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='func_perms', to='farmbase.FunctionModule', verbose_name='模块')),
                ('users', models.ManyToManyField(related_name='func_perms', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '功能模块权限',
                'ordering': ('module__name', 'codename'),
            },
        ),
        migrations.CreateModel(
            name='UrlPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('view_name', models.CharField(max_length=100, verbose_name='view_name')),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=20, null=True, verbose_name='请求方法')),
                ('perm_required', models.BooleanField(default=False, verbose_name='是否需要权限校验')),
                ('groups', models.ManyToManyField(blank=True, related_name='url_perms', to='auth.Group', verbose_name='用户组')),
                ('users', models.ManyToManyField(blank=True, related_name='url_perms', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'URL权限',
                'ordering': ['view_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='urlpermission',
            unique_together=set([('view_name', 'method')]),
        ),
    ]
