# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0008_assign_proposals_func_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlpermission',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='urlpermission',
            name='users',
        ),
        migrations.RemoveField(
            model_name='urlpermission',
            name='perm_required',
        ),
        migrations.AddField(
            model_name='functionpermission',
            name='urls',
            field=models.ManyToManyField(related_name='func_perms', to='farmbase.UrlPermission', verbose_name='urls'),
        ),
    ]
