# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0011_set_tpm_board_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='接受项目最大数'),
        ),
    ]
