# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-23 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0012_profile_project_capacity'),
        ('farmbase', '0006_create_token_for_users'),
    ]

    operations = [
    ]
