# Generated by Django 2.0 on 2018-11-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0013_merge_20180823_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionpermission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='func_perms', to='farmbase.FunctionModule', verbose_name='模块'),
        ),
    ]
