# Generated by Django 2.0 on 2019-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0014_auto_20181118_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(blank=True, choices=[('#212736', 'Black'), ('#2161FD', 'Blue'), ('#36B37E', 'Green'), ('#F5121D', 'Red'), ('#FE802F', 'Orange'), ('#9254DE', 'Purple'), ('#EB2F96', 'Magenta')], max_length=10, null=True, verbose_name='头像颜色'),
        ),
    ]
