# Generated by Django 2.0 on 2019-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0016_update_func_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gitlab_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='对应gitlab账户的id'),
        ),
    ]
