# Generated by Django 2.0 on 2019-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0017_profile_gitlab_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gitlab_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='对应gitlab账户的id'),
        ),
    ]
