# Generated by Django 2.0 on 2019-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbase', '0018_auto_20190909_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feishu_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='飞书ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dd_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='钉钉ID'),
        ),
    ]
