# Generated by Django 2.0 on 2020-06-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0043_data_migrate_documents_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='密钥')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Token',
            },
        ),
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_user', to='developers.Developer', verbose_name='自由工程师')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_user', to=settings.AUTH_USER_MODEL, verbose_name='内部员工')),
            ],
            options={
                'verbose_name': '顶层用户',
            },
        ),
        migrations.AddField(
            model_name='toptoken',
            name='top_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_token', to='auth_top.TopUser', verbose_name='顶层用户'),
        ),
    ]
