# Generated by Django 2.0 on 2020-06-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0002_auto_20200619_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
