# Generated by Django 2.0 on 2020-08-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_client'),
        ('auth_top', '0003_auto_20200619_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuser',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_user', to='clients.Client', verbose_name='客户'),
        ),
    ]
