# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0003_auto_20171224_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='callback_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='回调代号'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='任务来源对象id'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_tasks', to='contenttypes.ContentType', verbose_name='任务来源model'),
        ),
    ]
