# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-19 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180521_0037'),
        ('tasks', '0004_task_tags'),
    ]

    operations = [
    ]
