# Generated by Django 2.2.14 on 2021-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20201117_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('common', '普通'), ('lead_new_task', '线索新任务'), ('proposal_new_task', '需求新任务'), ('proposal_contact', '需求初次联系'), ('proposal_need_report', '需求需要报告'), ('project_payment', '项目收款'), ('project_position_need', '项目职位需求'), ('project_position_candidate', '项目职位需求候选人'), ('project_position_star_rating', '项目职位评分'), ('project_position_star_rating', '项目职位评分'), ('regular_contract_payment', '固定工程师合同')], default='common', max_length=50, verbose_name='任务类型'),
        ),
    ]
