# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-25 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='data',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='filename',
        ),
    ]
