# Generated by Django 2.0 on 2018-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20170925_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称'),
        ),
    ]
