# Generated by Django 2.0 on 2019-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20181205_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件'},
        ),
        migrations.AddField(
            model_name='file',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='后缀'),
        ),
    ]
