# Generated by Django 2.0 on 2020-05-27 18:29

from django.db import migrations, models
import files.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20190326_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(acl='public-read'), upload_to=files.models.PublicFile.generate_filename)),
                ('filename', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='后缀')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文件',
            },
        ),
    ]
