# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuaWeiVoiceCallAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='认证密码')),
                ('access_token', models.CharField(blank=True, max_length=180, null=True, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=180, null=True, verbose_name='刷新令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_in', models.CharField(default='', max_length=32, verbose_name='token有效期 单位为秒')),
            ],
            options={
                'verbose_name': '华为语音通话认证用户',
            },
        ),
    ]
