# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-13 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webphone.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0027_auto_20181101_2146'),
        ('webphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='主叫号码')),
                ('callee_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='被叫号码')),
                ('source', models.IntegerField(choices=[(1, '个人上传'), (2, '话单通知')], default=2, verbose_name='记录来源')),
                ('record_flag', models.IntegerField(choices=[(0, '未录音'), (1, '有录音')], default=0, verbose_name='录音标识')),
                ('record_date', models.DateField(blank=True, max_length=128, null=True, verbose_name='录音日期')),
                ('file', models.FileField(blank=True, null=True, upload_to=webphone.models.CallRecord.generate_filename)),
                ('filename', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
                ('file_suffix', models.CharField(blank=True, max_length=10, null=True, verbose_name='文件后缀')),
                ('number', models.IntegerField(default=1, verbose_name='编号')),
                ('record_start_time', models.DateTimeField(blank=True, null=True, verbose_name='录音开始时间')),
                ('record_file_download_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='录音文件下载地址')),
                ('download_url_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='录音文件下载地址更新时间')),
                ('record_object_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='录音文件名')),
                ('record_bucket_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='录音文件名所在的目录名')),
                ('record_domain', models.CharField(blank=True, max_length=128, null=True, verbose_name='存放录音文件的域名')),
                ('session_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='通话链路的会话标识')),
                ('icid', models.CharField(blank=True, max_length=64, null=True, verbose_name='呼叫记录标识')),
                ('uid', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('call_in_time', models.DateTimeField(blank=True, null=True, verbose_name='呼入开始时间')),
                ('call_end_time', models.DateTimeField(blank=True, null=True, verbose_name='呼叫结束时间')),
                ('call_out_answer_time', models.DateTimeField(blank=True, null=True, verbose_name='Initcall的呼出应答时间')),
                ('fwd_answer_time', models.DateTimeField(blank=True, null=True, verbose_name='转接应答时间')),
                ('fail_time', models.DateTimeField(blank=True, null=True, verbose_name='呼入、呼出的失败时间')),
                ('user_data', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to=settings.AUTH_USER_MODEL, verbose_name='主叫用户')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='proposals.Proposal', verbose_name='需求')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_call_records', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '通话记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
