# Generated by Django 2.0 on 2018-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphone', '0002_callrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_file_download_url',
            field=models.TextField(blank=True, null=True, verbose_name='录音文件下载地址'),
        ),
    ]
