# Generated by Django 2.0 on 2018-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphone', '0003_auto_20181119_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件大小'),
        ),
    ]
