# Generated by Django 2.0 on 2019-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphone', '0004_callrecord_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='call_duration',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='通话时长'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='number',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
    ]
