# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-03 15:13
from __future__ import unicode_literals

from django.db import migrations

def copy_logs_from_projects(apps, schema_editor):
    try:
        ProLog = apps.get_model("projects", "Log")
    except LookupError:
        return
    Log = apps.get_model("logs", "Log")
    for log in ProLog.objects.all():
        Log.objects.create(
            content_type=log.content_type,
            object_id=log.object_id,
            content=log.content,
            operator=log.operator,
            created_at=log.create_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_logs_from_projects, migrations.RunPython.noop),
    ]





