# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20171103_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
