# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-27 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20171103_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
    ]
