# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-10 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20171127_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '操作记录'},
        ),
    ]
