# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-11 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20180410_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
