# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-13 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20180411_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at'], 'verbose_name': '操作记录'},
        ),
    ]
