# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_browsinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置'),
        ),
    ]
