# Generated by Django 2.0 on 2019-05-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20181118_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content_data',
            field=models.TextField(blank=True, null=True, verbose_name='内容数据'),
        ),
    ]
