# Generated by Django 2.0 on 2019-05-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_auto_20190515_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
