# Generated by Django 2.0 on 2019-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_auto_20190522_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
