# Generated by Django 2.0 on 2019-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_migrate_logs_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
