# Generated by Django 2.0 on 2019-11-05 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0026_migrate_developers_is_active'),
        ('logs', '0016_migrate_browsing_histories_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='operator_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='developers.Developer', verbose_name='操作人-开发者'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人-Farm用户'),
        ),
    ]
