# Generated by Django 2.0 on 2019-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_auto_20191105_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='codename',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='代号'),
        ),
    ]
