# Generated by Django 2.0 on 2020-04-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_log_code_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browsinghistory',
            options={'ordering': ['-created_at'], 'verbose_name': '浏览记录'},
        ),
    ]
