# Generated by Django 2.0 on 2020-06-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_auto_20200420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operator_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='developers.Developer', verbose_name='操作人-工程师'),
        ),
    ]
