# Generated by Django 2.0 on 2020-08-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_top', '0004_topuser_client'),
        ('logs', '0021_log_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browsing_histories', to='auth_top.TopUser', verbose_name='浏览用户'),
        ),
    ]
