# Generated by Django 2.0 on 2019-01-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('playbook', '0003_auto_20171128_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, null=True, max_length=20, verbose_name='类型')),
                ('checked', models.BooleanField(default=False, verbose_name='完成')),
                ('skipped', models.BooleanField(default=False, verbose_name='跳过')),
                ('description', models.TextField(verbose_name='描述')),
                ('position', models.IntegerField(verbose_name='位置')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': 'Playbook检查项',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68, verbose_name='名称')),
                ('url', models.CharField(max_length=81, verbose_name='链接地址')),
                ('position', models.IntegerField(verbose_name='位置')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '链接',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='阶段名称')),
                ('position', models.IntegerField(verbose_name='位置')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='对应状态')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Playbook阶段',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['position'], 'verbose_name': 'Playbook检查项组'},
        ),
        migrations.AlterModelOptions(
            name='infoitem',
            options={'ordering': ['position'], 'verbose_name': 'Playbook注意项'},
        ),
        migrations.AddField(
            model_name='checkitem',
            name='check_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='playbook.ChecklistItem'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_groups', to='playbook.Stage'),
        ),
        migrations.AddField(
            model_name='infoitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_items', to='playbook.Stage'),
        ),
    ]
