# Generated by Django 2.0 on 2019-01-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0006_extract_links_from_project_playbook_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='对应状态'),
        ),
        migrations.AlterField(
            model_name='infoitem',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='对应状态'),
        ),
    ]
