# Generated by Django 2.0 on 2020-01-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0011_auto_20200115_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRevisionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_data', models.TextField(blank=True, null=True, verbose_name='内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Playbook模板修改记录',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_playbook_templates', to='playbook.Template', verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='templatecheckgroup',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_check_groups', to='playbook.TemplateCheckGroup', verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='templatecheckgroup',
            name='playbook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_groups', to='playbook.Template', verbose_name='Playbook模板'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_check_items', to='playbook.TemplateCheckItem', verbose_name='创建来源'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='playbook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='playbook.Template', verbose_name='Playbook模板'),
        ),
        migrations.AlterField(
            model_name='templatecheckgroup',
            name='template_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_groups', to='playbook.TemplateStage', verbose_name='Playbook模板阶段'),
        ),
        migrations.AddField(
            model_name='templaterevisionhistory',
            name='playbook_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='playbook.Template', verbose_name='Playbook模板'),
        ),
    ]
