# Generated by Django 2.0 on 2020-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0012_auto_20200120_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateinfoitem',
            name='template_check_item',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='注意事项'),
        ),
        migrations.DeleteModel(
            name='TemplateInfoItem',
        ),
    ]
