# Generated by Django 2.0 on 2020-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0013_auto_20200120_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='member_type',
            field=models.CharField(choices=[('manager', '项目经理'), ('product_manager', '产品经理')], default='product_manager', max_length=20, verbose_name='角色类型'),
        ),
        migrations.AddField(
            model_name='template',
            name='member_type',
            field=models.CharField(choices=[('manager', '项目经理'), ('product_manager', '产品经理')], default='product_manager', max_length=20, verbose_name='角色类型'),
        ),
    ]
