# Generated by Django 2.0 on 2020-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0015_migrate_playbook_templates_stages_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecheckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('会议', '会议'), ('Farm', 'Farm'), ('Quip', 'Quip'), ('GitLab', 'GitLab'), ('微信', '微信'), ('YApi', 'YApi'), ('Axure', 'Axure'), ('其他', '其他')], max_length=20, null=True, verbose_name='类型'),
        ),
    ]
