# Generated by Django 2.0 on 2020-03-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0016_auto_20200319_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='member_type',
            field=models.CharField(choices=[('manager', '项目经理'), ('product_manager', '产品')], default='product_manager', max_length=20, verbose_name='角色类型'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('proposal', '需求'), ('project', '项目')], max_length=15, verbose_name='模板类型'),
        ),
    ]
