# Generated by Django 2.0 on 2020-04-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0017_auto_20200320_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='templatestage',
            name='status',
        ),
    ]
