# Generated by Django 2.0 on 2020-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0018_auto_20200427_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计结束日期'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='expected_date_base',
            field=models.CharField(blank=True, choices=[('stage_start_date', '阶段开始日期'), ('stage_end_date', '阶段结束日期'), ('sprint_start_date', 'Sprint开始日期'), ('sprint_end_date', 'Sprint结束日期')], max_length=20, null=True, verbose_name='期望日期基准'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='expected_date_base_timedelta_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='期望日期基准间隔天数'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='expected_weekday',
            field=models.IntegerField(blank=True, null=True, verbose_name='每周任务期望周几'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='expected_date_base',
            field=models.CharField(blank=True, choices=[('stage_start_date', '阶段开始日期'), ('stage_end_date', '阶段结束日期'), ('sprint_start_date', 'Sprint开始日期'), ('sprint_end_date', 'Sprint结束日期')], max_length=20, null=True, verbose_name='期望日期基准'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='expected_date_base_timedelta_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='期望日期基准间隔天数'),
        ),
        migrations.AddField(
            model_name='templatecheckitem',
            name='expected_weekday',
            field=models.IntegerField(blank=True, null=True, verbose_name='每周任务期望周几'),
        ),
    ]
