# Generated by Django 2.0 on 2020-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0019_auto_20200529_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='阶段代号'),
        ),
        migrations.AddField(
            model_name='templatestage',
            name='stage_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='阶段代号'),
        ),
    ]
