# Generated by Django 2.0 on 2020-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0021_migrate_playbook_template_stage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='expected_weekday',
            field=models.IntegerField(blank=True, choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], null=True, verbose_name='每周任务期望周几'),
        ),
        migrations.AlterField(
            model_name='templatecheckitem',
            name='expected_weekday',
            field=models.IntegerField(blank=True, choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], null=True, verbose_name='每周任务期望周几'),
        ),
    ]
