# Generated by Django 2.2.14 on 2021-03-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0180_auto_20210224_1158'),
        ('playbook', '0023_auto_20200601_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='project_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,related_name='playbook_stages', to='projects.ProjectStage', verbose_name='项目阶段')
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_code',
            field=models.CharField(blank=True, choices=[('pending', '等待认领'), ('contact', '等待沟通'), ('ongoing', '进行中'), ('biz_opp', '商机'), ('contract', '成单交接'), ('deal', '成单'), ('no_deal', '未成单'), ('prd', '原型'), ('design', '设计'), ('development', '开发'), ('test', '测试'), ('acceptance', '验收'), ('completion', '完成')], max_length=20, null=True, verbose_name='阶段代号'),
        ),
        migrations.AlterField(
            model_name='templatestage',
            name='stage_code',
            field=models.CharField(blank=True, choices=[('pending', '等待认领'), ('contact', '等待沟通'), ('ongoing', '进行中'), ('biz_opp', '商机'), ('contract', '成单交接'), ('deal', '成单'), ('no_deal', '未成单'), ('prd', '原型'), ('design', '设计'), ('development', '开发'), ('test', '测试'), ('acceptance', '验收'), ('completion', '完成')], max_length=20, null=True, verbose_name='阶段代号'),
        ),
    ]
