# Generated by Django 2.2.14 on 2021-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0025_migrate_playbook_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_code',
            field=models.CharField(blank=True, choices=[('pending', '等待认领'), ('contact', '等待沟通'), ('ongoing', '进行中'), ('biz_opp', '商机'), ('contract', '成单交接'), ('deal', '成单'), ('no_deal', '未成单'), ('prd', '原型'), ('design', '设计'), ('development', '开发'), ('test', '测试'), ('acceptance', '验收')], max_length=20, null=True, verbose_name='阶段代号'),
        ),
        migrations.AlterField(
            model_name='templatestage',
            name='stage_code',
            field=models.CharField(blank=True, choices=[('pending', '等待认领'), ('contact', '等待沟通'), ('ongoing', '进行中'), ('biz_opp', '商机'), ('contract', '成单交接'), ('deal', '成单'), ('no_deal', '未成单'), ('prd', '原型'), ('design', '设计'), ('development', '开发'), ('test', '测试'), ('acceptance', '验收')], max_length=20, null=True, verbose_name='阶段代号'),
        ),
    ]
