# Generated by Django 2.2.14 on 2021-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0027_migrate_playbook_check_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='expected_date_base',
            field=models.CharField(blank=True, choices=[('stage_start_date', '阶段开始日期'), ('stage_end_date', '阶段结束日期')], max_length=20, null=True, verbose_name='期望日期基准'),
        ),
        migrations.AlterField(
            model_name='templatecheckitem',
            name='expected_date_base',
            field=models.CharField(blank=True, choices=[('stage_start_date', '阶段开始日期'), ('stage_end_date', '阶段结束日期')], max_length=20, null=True, verbose_name='期望日期基准'),
        ),
        migrations.AlterField(
            model_name='templatecheckitem',
            name='period',
            field=models.CharField(choices=[('once', '一次性任务'), ('weekly', '每周任务')], default='once', max_length=15, verbose_name='周期'),
        ),
    ]
