# Generated by Django 2.2.14 on 2021-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0028_auto_20210315_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecheckitem',
            name='type',
            field=models.CharField(blank=True, choices=[('会议', '会议'), ('Farm', 'Farm'), ('Quip', 'Quip'), ('GitLab', 'GitLab'), ('微信', '微信'), ('YApi', 'YApi'), ('飞书', '飞书'), ('Axure', 'Axure'), ('其他', '其他')], max_length=20, null=True, verbose_name='类型'),
        ),
    ]
