# Generated by Django 2.2.14 on 2021-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0029_auto_20210323_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='period',
            field=models.CharField(choices=[('once', '一次性任务'), ('weekly', '每周任务')], default='once', max_length=15, verbose_name='周期'),
        ),
    ]
