# Generated by Django 2.0 on 2020-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_migrate_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('normal', '普通'), ('important', '重要')], default='normal', max_length=15, verbose_name='优先级'),
        ),
    ]
