# Generated by Django 2.0 on 2020-06-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_need_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='developers.Developer', verbose_name='工程师'),
        ),
    ]
