# Generated by Django 2.0 on 2020-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='app_id',
            field=models.CharField(choices=[('gear_farm', 'Gear-Farm'), ('gear_developer', '开发者端'), ('gear_test', 'Gear-Test'), ('gear_client', '客户端')], default='gear_farm', max_length=15, verbose_name='app'),
        ),
    ]
