# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': (('view_all_developers', 'Can all developers'),)},
        ),
    ]
