# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-08 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20170802_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': (('view_all_developers', 'Can view all developers'),)},
        ),
    ]
