# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_data_init_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='developer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='developer',
            name='git',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Git'),
        ),
        migrations.AddField(
            model_name='developer',
            name='quip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quip'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='bank_info',
            field=models.TextField(blank=True, null=True, verbose_name='其他打款信息'),
        ),
    ]
