# -*- coding: utf-8 -*- 
# Generated by Django 1.10.2 on 2017-11-08 12:38 
from __future__ import unicode_literals 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('developers', '0006_data_migrate_bankinfo'), 
    ] 
 
    operations = [ 
        migrations.AlterField( 
            model_name='developer', 
            name='bank_info', 
            field=models.TextField(blank=True, null=True, verbose_name='打款信息'), 
        ), 
    ] 