# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0008_developer_fulltime_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': (('view_all_developers', 'Can view all developers'),), 'verbose_name': '工程师'},
        ),
    ]
