# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0009_auto_20171128_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': (('gear_view_all_developers', '查看全部工程师'),), 'verbose_name': '工程师'},
        ),
    ]
