# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0014_change_developers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='qq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ'),
        ),
    ]
