# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0015_auto_20180208_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='fadada',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='法大大'),
        ),
    ]
