# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 10:59
from __future__ import unicode_literals

import developers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0016_developer_fadada'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='developer',
            name='back_side_of_id_card',
            field=models.ImageField(blank=True, null=True, upload_to=developers.models.Developer.generate_filename, verbose_name='身份证反面照'),
        ),
        migrations.AddField(
            model_name='developer',
            name='front_side_of_id_card',
            field=models.ImageField(blank=True, null=True, upload_to=developers.models.Developer.generate_filename, verbose_name='身份证正面照'),
        ),
        migrations.AddField(
            model_name='developer',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地区'),
        ),
    ]
