# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0017_auto_20180828_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='roles',
            field=models.ManyToManyField(related_name='developers', to='developers.Role', verbose_name='职位'),
        ),
    ]
