# Generated by Django 2.0 on 2018-11-18 00:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0018_auto_20180903_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='development_languages',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='development_language_developer', through='developers.TaggedDevelopmentLanguage', to='taggit.Tag', verbose_name='开发语言'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='frameworks',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='framework_developer', through='developers.TaggedFrameworks', to='taggit.Tag', verbose_name='开发框架工具'),
        ),
    ]
