# Generated by Django 2.0 on 2019-01-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0019_auto_20181118_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '职位'},
        ),
    ]
