# Generated by Django 2.0 on 2019-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0020_auto_20190121_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='弃用时间'),
        ),
        migrations.AddField(
            model_name='developer',
            name='abandoned_reason',
            field=models.TextField(blank=True, null=True, verbose_name='弃用理由'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='expected_work_at',
            field=models.DateField(blank=True, null=True, verbose_name='预计可接单时间'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='status',
            field=models.CharField(choices=[('0', '弃用'), ('1', '可以接单'), ('2', '不可接单')], default='1', max_length=2, verbose_name='状态'),
        ),
    ]
