# Generated by Django 2.0 on 2019-07-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0021_auto_20190725_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='tel',
            new_name='phone',
        ),
    ]
