# Generated by Django 2.0 on 2019-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0022_auto_20190731_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='gitlab_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='GitLab账户'),
        ),
    ]
