# Generated by Django 2.0 on 2019-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0023_developer_gitlab_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='refuse_new_job_reason',
            field=models.TextField(blank=True, null=True, verbose_name='不可接单理由'),
        ),
    ]
