# Generated by Django 2.0 on 2019-11-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0024_developer_refuse_new_job_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this developer should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='developertoken',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='developers.Developer', verbose_name='Developer'),
        ),
    ]
