# Generated by Django 2.0 on 2019-11-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0026_migrate_developers_is_active'),
        ('developers', '0024_migrate_developer_role_development_language_framework'),
    ]

    operations = [
    ]
