# Generated by Django 2.0 on 2019-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0027_merge_20191107_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
