# Generated by Django 2.0 on 2019-11-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0028_auto_20191108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
