# Generated by Django 2.0 on 2020-01-16 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0029_developer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='developertoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='developertoken',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='developers.Developer', verbose_name='开发者'),
        ),
    ]
