# Generated by Django 2.0 on 2020-04-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0144_auto_20200313_1526'),
        ('developers', '0030_auto_20200116_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待'), ('postpone', '任务延期'), ('normal', '正常'), ('absence', '缺卡')], default='pending', max_length=15, verbose_name='日报状态')),
                ('day', models.DateField(verbose_name='日期')),
                ('leave_at', models.TimeField(blank=True, null=True, verbose_name='请假开始时间')),
                ('return_at', models.TimeField(blank=True, null=True, verbose_name='请假结束时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('punched_at', models.DateTimeField(blank=True, null=True, verbose_name='打卡时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_daily_works', to='developers.Developer', verbose_name='工程师')),
                ('next_day_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.DailyWork')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_works', to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '工作日报',
            },
        ),
        migrations.CreateModel(
            name='DailyWorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('gantt', '甘特图任务'), ('other', '其他任务')], default='other', max_length=15, verbose_name='工作类型')),
                ('catalogue_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='分类名称')),
                ('name', models.CharField(max_length=30, verbose_name='任务名称')),
                ('task_status', models.CharField(choices=[('pending', '未开始'), ('ongoing', '正在做'), ('done', '已完成')], default='pending', max_length=15, verbose_name='工作状态')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('only_workday', models.BooleanField(default=False, verbose_name='仅计算工作日')),
                ('expected_finish_time', models.DateField(blank=True, null=True, verbose_name='预计完成时间')),
                ('timedelta_days', models.FloatField(blank=True, null=True, verbose_name='任务持续天数')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='任务备注')),
                ('result_remarks', models.TextField(blank=True, null=True, verbose_name='任务结果备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('daily_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='developers.DailyWork', verbose_name='日报')),
                ('gantt_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_tasks', to='projects.GanttTaskTopic', verbose_name='甘特图任务')),
            ],
            options={
                'verbose_name': '日报任务',
            },
        ),
    ]
