# Generated by Django 2.0 on 2020-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0032_auto_20200415_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='need_submit_daily_work',
            field=models.BooleanField(default=True),
        ),
    ]
