# Generated by Django 2.0 on 2020-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0033_dailywork_need_submit_daily_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='need_support',
            field=models.BooleanField(default=False, verbose_name='是否需要项目组成员支持'),
        ),
    ]
