# Generated by Django 2.0 on 2020-05-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0034_dailywork_need_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developertoken',
            name='developer',
        ),
        migrations.DeleteModel(
            name='DeveloperToken',
        ),
    ]
