# Generated by Django 2.0 on 2020-06-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0035_auto_20200528_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文档标题')),
                ('version', models.CharField(blank=True, default='1.0', max_length=10, null=True, verbose_name='当前版本')),
                ('status', models.CharField(choices=[('online', '线上版本'), ('history', '历史版本')], default='online', max_length=15, verbose_name='状态')),
                ('importance', models.CharField(choices=[('general', '普通'), ('major', '重点')], default='general', max_length=15, verbose_name='重要性')),
                ('source', models.CharField(choices=[('quip_link', 'Quip链接')], default='quip_link', max_length=20, verbose_name='创建来源')),
                ('html', models.TextField(blank=True, null=True, verbose_name='来源html')),
                ('quip_doc_id', models.CharField(max_length=30, verbose_name='Quip文档ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开阅读')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('roles', models.ManyToManyField(related_name='documents', to='developers.Role', verbose_name='职位')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '工程师文档',
            },
        ),
    ]
