# Generated by Django 2.0 on 2020-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0036_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='first_version_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='第一版创建时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='version_mode',
            field=models.CharField(choices=[('mini', '小版本'), ('large', '大版本')], default='large', max_length=10, verbose_name='版本类型'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('online', '线上版本'), ('history', '历史版本'), ('deleted', '删除版本')], default='online', max_length=15, verbose_name='状态'),
        ),
    ]
