# Generated by Django 2.0 on 2020-06-04 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0037_auto_20200604_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_read_logs', to='developers.Developer', verbose_name='读者-工程师')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='developers.Document', verbose_name='文档')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_read_logs', to=settings.AUTH_USER_MODEL, verbose_name='读者-Farm用户')),
            ],
            options={
                'verbose_name': '工程师文档阅读记录',
            },
        ),
        migrations.CreateModel(
            name='DocumentSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sync_logs', to='developers.Developer', verbose_name='同步-工程师')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='developers.Document', verbose_name='文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='同步-Farm用户')),
            ],
            options={
                'verbose_name': '工程师文档同步沟通',
            },
        ),
    ]
