# Generated by Django 2.0 on 2020-06-05 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0038_documentreadlog_documentsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='1.0', max_length=10, null=True, verbose_name='版本号')),
                ('version_mode', models.CharField(choices=[('mini', '小版本'), ('large', '大版本')], default='large', max_length=10, verbose_name='版本类型')),
                ('status', models.CharField(choices=[('online', '线上版本'), ('history', '历史版本')], default='online', max_length=10, verbose_name='状态')),
                ('html', models.TextField(blank=True, null=True, verbose_name='来源html')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('source', models.CharField(default='quip_link', max_length=20, verbose_name='创建来源')),
                ('quip_doc_id', models.CharField(max_length=30, verbose_name='Quip文档ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文档版本',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='first_version_created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='html',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quip_doc_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version_mode',
        ),
        migrations.AddField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='文档标题'),
        ),
        migrations.AlterField(
            model_name='documentreadlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='developers.DocumentVersion', verbose_name='文档版本'),
        ),
        migrations.AlterField(
            model_name='documentsynclog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='developers.DocumentVersion', verbose_name='文档版本'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='developers.Document', verbose_name='文档'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
