# Generated by Django 2.0 on 2020-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0039_auto_20200605_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='clean_html',
            field=models.TextField(blank=True, null=True, verbose_name='来源html'),
        ),
    ]
