# Generated by Django 2.0 on 2020-06-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0040_documentversion_clean_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': '工程师'},
        ),
    ]
