# Generated by Django 2.0 on 2020-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0041_auto_20200609_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
