# Generated by Django 2.0 on 2020-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0043_data_migrate_documents_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='avatar_color',
            field=models.CharField(blank=True, choices=[('#212736', 'Black'), ('#2161FD', 'Blue'), ('#36B37E', 'Green'), ('#F5121D', 'Red'), ('#FE802F', 'Orange'), ('#9254DE', 'Purple'), ('#EB2F96', 'Magenta')], max_length=10, null=True, verbose_name='头像颜色'),
        ),
    ]
