# Generated by Django 2.0 on 2020-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0045_migrate_developer_role_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='feishu_user_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='飞书ID'),
        ),
    ]
