# Generated by Django 2.0 on 2020-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0046_developer_feishu_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='payee_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人收款账号'),
        ),
        migrations.AddField(
            model_name='developer',
            name='payee_id_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收款人身份证号码'),
        ),
        migrations.AddField(
            model_name='developer',
            name='payee_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='收款人户名'),
        ),
        migrations.AddField(
            model_name='developer',
            name='payee_opening_bank',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='收款人开户行'),
        ),
        migrations.AddField(
            model_name='developer',
            name='payee_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收款人手机号'),
        ),
    ]
