# Generated by Django 2.0 on 2020-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0047_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='payee_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收款人户名'),
        ),
    ]
