# Generated by Django 2.2.14 on 2021-02-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0050_data_migrate_developers_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='gitlab_commits',
            field=models.TextField(blank=True, null=True, verbose_name='代码提交'),
        ),
    ]
