# Generated by Django 2.2.14 on 2021-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0051_dailywork_gitlab_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='esign_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工程师签署账户id'),
        ),
    ]
