# Generated by Django 2.2.14 on 2021-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0052_developer_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_real_name_auth',
            field=models.BooleanField(default=False, verbose_name='是否已经实名认证'),
        ),
    ]
