# Generated by Django 2.2.14 on 2021-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0054_developer_real_name_auth_status_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
