# Generated by Django 2.2.14 on 2021-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0055_auto_20210414_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='name_pinyin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称拼音'),
        ),
    ]
